packages:
  - frontend

ignoreWorkspaceRootCheck: true

updateConfig:
  ignoreDependencies:
    - "@types/node"

allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  oxc-resolver: true

peerDependencyRules:
  allowedVersions:
    "@react-router/dev>typescript": ">=7 <8"
    "@react-router/node>typescript": ">=7 <8"

minimumReleaseAgeExclude:
  - typescript@7.0.2
