// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachAgentToCollection(arg1) {
  return window['go']['main']['AgentStoreWrapper']['AttachAgentToCollection'](arg1);
}

export function CreateAgentCollection(arg1) {
  return window['go']['main']['AgentStoreWrapper']['CreateAgentCollection'](arg1);
}

export function CreateManagedAgent(arg1) {
  return window['go']['main']['AgentStoreWrapper']['CreateManagedAgent'](arg1);
}

export function DeleteAgentCollection(arg1, arg2) {
  return window['go']['main']['AgentStoreWrapper']['DeleteAgentCollection'](arg1, arg2);
}

export function DeleteManagedAgent(arg1) {
  return window['go']['main']['AgentStoreWrapper']['DeleteManagedAgent'](arg1);
}

export function DetachAgentFromCollection(arg1) {
  return window['go']['main']['AgentStoreWrapper']['DetachAgentFromCollection'](arg1);
}

export function GetAgent(arg1) {
  return window['go']['main']['AgentStoreWrapper']['GetAgent'](arg1);
}

export function GetAgentCollection(arg1) {
  return window['go']['main']['AgentStoreWrapper']['GetAgentCollection'](arg1);
}

export function ListAgentCollections(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ListAgentCollections'](arg1);
}

export function ListAgents(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ListAgents'](arg1);
}

export function ListAgentsForManagement() {
  return window['go']['main']['AgentStoreWrapper']['ListAgentsForManagement']();
}

export function ListDirectAgentMemberships(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ListDirectAgentMemberships'](arg1);
}

export function ReplaceManagedAgent(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ReplaceManagedAgent'](arg1);
}

export function ResolveAgent(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ResolveAgent'](arg1);
}

export function ResolveAgentCapabilities(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ResolveAgentCapabilities'](arg1);
}

export function ResolveAgentCollection(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ResolveAgentCollection'](arg1);
}

export function SetAgentCollectionEnabled(arg1, arg2, arg3) {
  return window['go']['main']['AgentStoreWrapper']['SetAgentCollectionEnabled'](arg1, arg2, arg3);
}

export function SetAgentEnabled(arg1, arg2, arg3) {
  return window['go']['main']['AgentStoreWrapper']['SetAgentEnabled'](arg1, arg2, arg3);
}

export function UpdateAgentCollection(arg1) {
  return window['go']['main']['AgentStoreWrapper']['UpdateAgentCollection'](arg1);
}
