// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collection} from '../models';
import {consumerapi} from '../models';
import {model} from '../models';

export function AddAgentCollectionArtifactMember(arg1:collection.AddArtifactMemberRequest):Promise<collection.CollectionView>;

export function AddAgentCollectionMember(arg1:collection.AddMemberRequest):Promise<collection.CollectionView>;

export function CommitAgentImport(arg1:consumerapi.AgentImportCommitRequest):Promise<consumerapi.AgentImportCommitResult>;

export function CreateAgentCollection(arg1:collection.CreateRequest):Promise<collection.CollectionView>;

export function DeleteAgentCollection(arg1:model.ArtifactRef,arg2:number):Promise<void>;

export function DeleteManagedAgent(arg1:consumerapi.ManagedAgentDeleteRequest):Promise<void>;

export function ExportAgent(arg1:consumerapi.AgentExportRequest):Promise<consumerapi.AgentExportResult>;

export function GetAgent(arg1:model.ArtifactRef):Promise<consumerapi.AgentView>;

export function GetAgentCollection(arg1:model.ArtifactRef):Promise<collection.CollectionView>;

export function ListAgentCollectionMembers(arg1:model.ArtifactRef):Promise<collection.CollectionCapabilityPlan>;

export function ListAgentCollections(arg1:model.RootID):Promise<Array<collection.ListItem>>;

export function ListAgentCollectionsForManagement():Promise<Array<collection.ListItem>>;

export function ListAgentImportDestinations():Promise<Array<consumerapi.AgentImportDestination>>;

export function ListAgents(arg1:consumerapi.ListAgentsRequest):Promise<Array<consumerapi.AgentListItem>>;

export function ListAgentsForManagement():Promise<Array<consumerapi.AgentListItem>>;

export function MaterializeAgentText(arg1:model.ArtifactRef):Promise<consumerapi.AgentTextMaterialization>;

export function PreviewAgentImport(arg1:consumerapi.AgentImportPreviewRequest):Promise<consumerapi.AgentImportPreview>;

export function RemoveAgentCollectionMember(arg1:collection.RemoveMemberRequest):Promise<collection.CollectionView>;

export function ResolveAgent(arg1:model.ArtifactRef):Promise<consumerapi.AgentResolution>;

export function ResolveAgentCapabilities(arg1:model.ArtifactRef):Promise<consumerapi.AgentCapabilityPlan>;

export function SetAgentCollectionEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<collection.CollectionView>;

export function SetAgentEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<consumerapi.AgentView>;

export function UpdateAgentCollection(arg1:collection.UpdateRequest):Promise<collection.CollectionView>;
