// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAgentCollectionArtifactMember(arg1) {
  return window['go']['main']['AgentStoreWrapper']['AddAgentCollectionArtifactMember'](arg1);
}

export function AddAgentCollectionMember(arg1) {
  return window['go']['main']['AgentStoreWrapper']['AddAgentCollectionMember'](arg1);
}

export function CommitAgentImport(arg1) {
  return window['go']['main']['AgentStoreWrapper']['CommitAgentImport'](arg1);
}

export function CreateAgentCollection(arg1) {
  return window['go']['main']['AgentStoreWrapper']['CreateAgentCollection'](arg1);
}

export function DeleteAgentCollection(arg1, arg2) {
  return window['go']['main']['AgentStoreWrapper']['DeleteAgentCollection'](arg1, arg2);
}

export function DeleteManagedAgent(arg1) {
  return window['go']['main']['AgentStoreWrapper']['DeleteManagedAgent'](arg1);
}

export function ExportAgent(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ExportAgent'](arg1);
}

export function GetAgent(arg1) {
  return window['go']['main']['AgentStoreWrapper']['GetAgent'](arg1);
}

export function GetAgentCollection(arg1) {
  return window['go']['main']['AgentStoreWrapper']['GetAgentCollection'](arg1);
}

export function ListAgentCollectionMembers(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ListAgentCollectionMembers'](arg1);
}

export function ListAgentCollections(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ListAgentCollections'](arg1);
}

export function ListAgentCollectionsForManagement() {
  return window['go']['main']['AgentStoreWrapper']['ListAgentCollectionsForManagement']();
}

export function ListAgentImportDestinations() {
  return window['go']['main']['AgentStoreWrapper']['ListAgentImportDestinations']();
}

export function ListAgents(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ListAgents'](arg1);
}

export function ListAgentsForManagement() {
  return window['go']['main']['AgentStoreWrapper']['ListAgentsForManagement']();
}

export function MaterializeAgentText(arg1) {
  return window['go']['main']['AgentStoreWrapper']['MaterializeAgentText'](arg1);
}

export function PreviewAgentImport(arg1) {
  return window['go']['main']['AgentStoreWrapper']['PreviewAgentImport'](arg1);
}

export function RemoveAgentCollectionMember(arg1) {
  return window['go']['main']['AgentStoreWrapper']['RemoveAgentCollectionMember'](arg1);
}

export function ResolveAgent(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ResolveAgent'](arg1);
}

export function ResolveAgentCapabilities(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ResolveAgentCapabilities'](arg1);
}

export function SetAgentCollectionEnabled(arg1, arg2, arg3) {
  return window['go']['main']['AgentStoreWrapper']['SetAgentCollectionEnabled'](arg1, arg2, arg3);
}

export function SetAgentEnabled(arg1, arg2, arg3) {
  return window['go']['main']['AgentStoreWrapper']['SetAgentEnabled'](arg1, arg2, arg3);
}

export function UpdateAgentCollection(arg1) {
  return window['go']['main']['AgentStoreWrapper']['UpdateAgentCollection'](arg1);
}
