// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugin} from '../models';
import {agent} from '../models';
import {model} from '../models';

export function AddAgentPluginArtifactMember(arg1:plugin.AddArtifactMemberRequest):Promise<plugin.PluginView>;

export function AddAgentPluginMember(arg1:plugin.AddMemberRequest):Promise<plugin.PluginView>;

export function CommitAgentImport(arg1:agent.AgentImportCommitRequest):Promise<agent.AgentImportCommitResult>;

export function CreateAgentPlugin(arg1:plugin.CreateRequest):Promise<plugin.PluginView>;

export function DeleteAgentPlugin(arg1:model.ArtifactRef,arg2:number):Promise<void>;

export function DeleteManagedAgent(arg1:agent.ManagedAgentDeleteRequest):Promise<void>;

export function ExportAgent(arg1:agent.AgentExportRequest):Promise<agent.AgentExportResult>;

export function GetAgent(arg1:model.ArtifactRef):Promise<agent.AgentView>;

export function GetAgentPlugin(arg1:model.ArtifactRef):Promise<plugin.PluginView>;

export function ListAgentImportDestinations():Promise<Array<agent.AgentImportDestination>>;

export function ListAgentPluginMembers(arg1:model.ArtifactRef):Promise<plugin.DirectMembership>;

export function ListAgentPlugins(arg1:model.RootID):Promise<Array<plugin.ListItem>>;

export function ListAgentPluginsForManagement():Promise<Array<plugin.ListItem>>;

export function ListAgents(arg1:agent.ListAgentsRequest):Promise<Array<agent.AgentListItem>>;

export function ListAgentsForManagement():Promise<Array<agent.AgentListItem>>;

export function PreviewAgentImport(arg1:agent.AgentImportPreviewRequest):Promise<agent.AgentImportPreview>;

export function RemoveAgentPluginMember(arg1:plugin.RemoveMemberRequest):Promise<plugin.PluginView>;

export function ResolveAgent(arg1:model.ArtifactRef):Promise<agent.AgentResolution>;

export function ResolveAgentCapabilities(arg1:model.ArtifactRef):Promise<agent.AgentCapabilityPlan>;

export function ResolveAgentPluginCapabilities(arg1:model.ArtifactRef):Promise<plugin.PluginCapabilityPlan>;

export function SetAgentEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<agent.AgentView>;

export function SetAgentPluginEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<plugin.PluginView>;

export function UpdateAgentPlugin(arg1:plugin.UpdateRequest):Promise<plugin.PluginView>;
