// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAgentPluginArtifactMember(arg1) {
  return window['go']['main']['AgentStoreWrapper']['AddAgentPluginArtifactMember'](arg1);
}

export function AddAgentPluginMember(arg1) {
  return window['go']['main']['AgentStoreWrapper']['AddAgentPluginMember'](arg1);
}

export function CommitAgentImport(arg1) {
  return window['go']['main']['AgentStoreWrapper']['CommitAgentImport'](arg1);
}

export function CreateAgentPlugin(arg1) {
  return window['go']['main']['AgentStoreWrapper']['CreateAgentPlugin'](arg1);
}

export function DeleteAgentPlugin(arg1, arg2) {
  return window['go']['main']['AgentStoreWrapper']['DeleteAgentPlugin'](arg1, arg2);
}

export function DeleteManagedAgent(arg1) {
  return window['go']['main']['AgentStoreWrapper']['DeleteManagedAgent'](arg1);
}

export function ExportAgent(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ExportAgent'](arg1);
}

export function GetAgent(arg1) {
  return window['go']['main']['AgentStoreWrapper']['GetAgent'](arg1);
}

export function GetAgentPlugin(arg1) {
  return window['go']['main']['AgentStoreWrapper']['GetAgentPlugin'](arg1);
}

export function ListAgentImportDestinations() {
  return window['go']['main']['AgentStoreWrapper']['ListAgentImportDestinations']();
}

export function ListAgentPluginMembers(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ListAgentPluginMembers'](arg1);
}

export function ListAgentPlugins(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ListAgentPlugins'](arg1);
}

export function ListAgentPluginsForManagement() {
  return window['go']['main']['AgentStoreWrapper']['ListAgentPluginsForManagement']();
}

export function ListAgents(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ListAgents'](arg1);
}

export function ListAgentsForManagement() {
  return window['go']['main']['AgentStoreWrapper']['ListAgentsForManagement']();
}

export function PreviewAgentImport(arg1) {
  return window['go']['main']['AgentStoreWrapper']['PreviewAgentImport'](arg1);
}

export function RemoveAgentPluginMember(arg1) {
  return window['go']['main']['AgentStoreWrapper']['RemoveAgentPluginMember'](arg1);
}

export function ResolveAgent(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ResolveAgent'](arg1);
}

export function ResolveAgentCapabilities(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ResolveAgentCapabilities'](arg1);
}

export function ResolveAgentPluginCapabilities(arg1) {
  return window['go']['main']['AgentStoreWrapper']['ResolveAgentPluginCapabilities'](arg1);
}

export function SetAgentEnabled(arg1, arg2, arg3) {
  return window['go']['main']['AgentStoreWrapper']['SetAgentEnabled'](arg1, arg2, arg3);
}

export function SetAgentPluginEnabled(arg1, arg2, arg3) {
  return window['go']['main']['AgentStoreWrapper']['SetAgentPluginEnabled'](arg1, arg2, arg3);
}

export function UpdateAgentPlugin(arg1) {
  return window['go']['main']['AgentStoreWrapper']['UpdateAgentPlugin'](arg1);
}
