// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function CancelCompletion(arg1:string):Promise<void>;

export function DeleteAuthKey(arg1:spec.DeleteAuthKeyRequest):Promise<spec.DeleteAuthKeyResponse>;

export function DeleteProviderPreset(arg1:spec.DeleteProviderPresetRequest):Promise<spec.DeleteProviderPresetResponse>;

export function FetchCompletion(arg1:string,arg2:string,arg3:spec.CompletionRequestBody,arg4:string,arg5:string,arg6:string):Promise<spec.CompletionResponse>;

export function PutProviderPreset(arg1:spec.PutProviderPresetRequest):Promise<spec.PutProviderPresetResponse>;

export function SetAuthKey(arg1:spec.SetAuthKeyRequest):Promise<spec.SetAuthKeyResponse>;
