// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCompletion(arg1) {
  return window['go']['main']['AggregrateWrapper']['CancelCompletion'](arg1);
}

export function DeleteAuthKey(arg1) {
  return window['go']['main']['AggregrateWrapper']['DeleteAuthKey'](arg1);
}

export function DeleteProviderPreset(arg1) {
  return window['go']['main']['AggregrateWrapper']['DeleteProviderPreset'](arg1);
}

export function FetchCompletion(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['AggregrateWrapper']['FetchCompletion'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PutProviderPreset(arg1) {
  return window['go']['main']['AggregrateWrapper']['PutProviderPreset'](arg1);
}

export function SetAuthKey(arg1) {
  return window['go']['main']['AggregrateWrapper']['SetAuthKey'](arg1);
}
