// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateArtifactRoot(arg1) {
  return window['go']['main']['ArtifactStoreWrapper']['CreateArtifactRoot'](arg1);
}

export function CreateArtifactSource(arg1) {
  return window['go']['main']['ArtifactStoreWrapper']['CreateArtifactSource'](arg1);
}

export function GetArtifactRoot(arg1) {
  return window['go']['main']['ArtifactStoreWrapper']['GetArtifactRoot'](arg1);
}

export function GetArtifactSource(arg1) {
  return window['go']['main']['ArtifactStoreWrapper']['GetArtifactSource'](arg1);
}

export function ListArtifactRoots(arg1) {
  return window['go']['main']['ArtifactStoreWrapper']['ListArtifactRoots'](arg1);
}

export function ListArtifactSourceKinds(arg1) {
  return window['go']['main']['ArtifactStoreWrapper']['ListArtifactSourceKinds'](arg1);
}

export function ListArtifactSources(arg1) {
  return window['go']['main']['ArtifactStoreWrapper']['ListArtifactSources'](arg1);
}

export function PurgeArtifactRoot(arg1) {
  return window['go']['main']['ArtifactStoreWrapper']['PurgeArtifactRoot'](arg1);
}

export function PurgeArtifactSource(arg1) {
  return window['go']['main']['ArtifactStoreWrapper']['PurgeArtifactSource'](arg1);
}

export function RetireArtifactRoot(arg1) {
  return window['go']['main']['ArtifactStoreWrapper']['RetireArtifactRoot'](arg1);
}

export function RetireArtifactSource(arg1) {
  return window['go']['main']['ArtifactStoreWrapper']['RetireArtifactSource'](arg1);
}

export function Store() {
  return window['go']['main']['ArtifactStoreWrapper']['Store']();
}

export function UpdateArtifactRoot(arg1) {
  return window['go']['main']['ArtifactStoreWrapper']['UpdateArtifactRoot'](arg1);
}

export function UpdateArtifactSource(arg1) {
  return window['go']['main']['ArtifactStoreWrapper']['UpdateArtifactSource'](arg1);
}
