// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function DeleteAssistantPreset(arg1:spec.DeleteAssistantPresetRequest):Promise<spec.DeleteAssistantPresetResponse>;

export function DeleteAssistantPresetBundle(arg1:spec.DeleteAssistantPresetBundleRequest):Promise<spec.DeleteAssistantPresetBundleResponse>;

export function GetAssistantPreset(arg1:spec.GetAssistantPresetRequest):Promise<spec.GetAssistantPresetResponse>;

export function ListAssistantPresetBundles(arg1:spec.ListAssistantPresetBundlesRequest):Promise<spec.ListAssistantPresetBundlesResponse>;

export function ListAssistantPresets(arg1:spec.ListAssistantPresetsRequest):Promise<spec.ListAssistantPresetsResponse>;

export function PatchAssistantPreset(arg1:spec.PatchAssistantPresetRequest):Promise<spec.PatchAssistantPresetResponse>;

export function PatchAssistantPresetBundle(arg1:spec.PatchAssistantPresetBundleRequest):Promise<spec.PatchAssistantPresetBundleResponse>;

export function PutAssistantPreset(arg1:spec.PutAssistantPresetRequest):Promise<spec.PutAssistantPresetResponse>;

export function PutAssistantPresetBundle(arg1:spec.PutAssistantPresetBundleRequest):Promise<spec.PutAssistantPresetBundleResponse>;
