// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAssistantPreset(arg1) {
  return window['go']['main']['AssistantPresetStoreWrapper']['DeleteAssistantPreset'](arg1);
}

export function DeleteAssistantPresetBundle(arg1) {
  return window['go']['main']['AssistantPresetStoreWrapper']['DeleteAssistantPresetBundle'](arg1);
}

export function GetAssistantPreset(arg1) {
  return window['go']['main']['AssistantPresetStoreWrapper']['GetAssistantPreset'](arg1);
}

export function ListAssistantPresetBundles(arg1) {
  return window['go']['main']['AssistantPresetStoreWrapper']['ListAssistantPresetBundles'](arg1);
}

export function ListAssistantPresets(arg1) {
  return window['go']['main']['AssistantPresetStoreWrapper']['ListAssistantPresets'](arg1);
}

export function PatchAssistantPreset(arg1) {
  return window['go']['main']['AssistantPresetStoreWrapper']['PatchAssistantPreset'](arg1);
}

export function PatchAssistantPresetBundle(arg1) {
  return window['go']['main']['AssistantPresetStoreWrapper']['PatchAssistantPresetBundle'](arg1);
}

export function PutAssistantPreset(arg1) {
  return window['go']['main']['AssistantPresetStoreWrapper']['PutAssistantPreset'](arg1);
}

export function PutAssistantPresetBundle(arg1) {
  return window['go']['main']['AssistantPresetStoreWrapper']['PutAssistantPresetBundle'](arg1);
}
