// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {artifact} from '../models';
import {main} from '../models';
import {spec} from '../models';

export function CancelCompletion(arg1:string):Promise<void>;

export function FetchCompletion(arg1:artifact.ArtifactRef,arg2:main.CompletionRequestBody,arg3:string,arg4:string,arg5:string):Promise<spec.CompletionResponse>;
