// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';
import {artifact} from '../models';
import {consumerapi} from '../models';
import {secret} from '../models';
import {policy} from '../models';
import {auth} from '../models';
import {aggregate} from '../models';
import {root} from '../models';

export function ArtifactRefForRuntimeServerID(arg1:server.ServerID):Promise<artifact.ArtifactRef>;

export function CreateManagedMCP(arg1:consumerapi.ManagedMCPCreateRequest):Promise<consumerapi.ManagedMCPCreateResult>;

export function DeleteMCPServerSecret(arg1:artifact.ArtifactRef,arg2:secret.MCPSecretKind,arg3:string):Promise<void>;

export function GetMCPEffectivePolicy(arg1:artifact.ArtifactRef):Promise<policy.Effective>;

export function GetMCPServerAuthHealth(arg1:artifact.ArtifactRef):Promise<auth.MCPAuthHealth>;

export function PurgeManagedMCP(arg1:artifact.ArtifactRef,arg2:number):Promise<void>;

export function PurgeManagedMCPPolicy(arg1:artifact.ArtifactRef,arg2:number):Promise<void>;

export function PutMCPServerSecret(arg1:artifact.ArtifactRef,arg2:secret.MCPSecretKind,arg3:string,arg4:string):Promise<aggregate.SecretWriteResult>;

export function ReplaceManagedMCP(arg1:consumerapi.ManagedMCPReplaceRequest):Promise<consumerapi.ManagedMCPReplaceResult>;

export function RootIDForRuntimeCatalogID(arg1:server.CatalogID):Promise<root.RootID>;

export function RuntimeServerIDForArtifact(arg1:artifact.ArtifactRef):Promise<server.ServerID>;

export function UpdateMCPServerInstallation(arg1:artifact.ArtifactRef,arg2:number,arg3:server.ServerData):Promise<artifact.Artifact>;

export function UpdateProtectedMCPServerInstallation(arg1:artifact.ArtifactRef,arg2:number,arg3:server.ServerData):Promise<void>;

export function UpsertManagedMCPPolicy(arg1:consumerapi.ManagedMCPPolicyUpsertRequest):Promise<consumerapi.ManagedMCPPolicyUpsertResult>;
