// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';
import {mcp} from '../models';
import {server} from '../models';

export function ClearMCPServerSecret(arg1:model.ArtifactRef,arg2:string):Promise<main.MCPServerDetails>;

export function CreateMCPServer(arg1:mcp.ManagedMCPCreateRequest):Promise<mcp.ManagedMCPCreateResult>;

export function DeleteMCPPolicy(arg1:model.ArtifactRef,arg2:number):Promise<void>;

export function DeleteMCPServer(arg1:model.ArtifactRef,arg2:number):Promise<void>;

export function GetMCPServer(arg1:model.ArtifactRef):Promise<main.MCPServerDetails>;

export function GetMCPServersForRuntimeServers(arg1:Array<server.ServerID>):Promise<Array<main.MCPServerRuntimeDetails>>;

export function ListMCPPluginServers(arg1:model.ArtifactRef):Promise<Array<main.MCPServerDetails>>;

export function SaveMCPPolicy(arg1:mcp.ManagedMCPPolicyUpsertRequest):Promise<mcp.ManagedMCPPolicyUpsertResult>;

export function SaveMCPServerSettings(arg1:model.ArtifactRef,arg2:number,arg3:server.ServerData):Promise<main.MCPServerDetails>;

export function SetMCPServerSecret(arg1:model.ArtifactRef,arg2:string,arg3:string):Promise<main.MCPServerDetails>;

export function UpdateMCPServer(arg1:mcp.ManagedMCPReplaceRequest):Promise<mcp.ManagedMCPReplaceResult>;
