// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArtifactRefForRuntimeServerID(arg1) {
  return window['go']['main']['MCPAggregateWrapper']['ArtifactRefForRuntimeServerID'](arg1);
}

export function DeleteMCPServerSecret(arg1, arg2, arg3) {
  return window['go']['main']['MCPAggregateWrapper']['DeleteMCPServerSecret'](arg1, arg2, arg3);
}

export function GetMCPServerAuthHealth(arg1) {
  return window['go']['main']['MCPAggregateWrapper']['GetMCPServerAuthHealth'](arg1);
}

export function PutMCPServerSecret(arg1, arg2, arg3, arg4) {
  return window['go']['main']['MCPAggregateWrapper']['PutMCPServerSecret'](arg1, arg2, arg3, arg4);
}

export function RootIDForRuntimeCatalogID(arg1) {
  return window['go']['main']['MCPAggregateWrapper']['RootIDForRuntimeCatalogID'](arg1);
}

export function RuntimeServerIDForArtifact(arg1) {
  return window['go']['main']['MCPAggregateWrapper']['RuntimeServerIDForArtifact'](arg1);
}

export function UpdateMCPServerInstallation(arg1, arg2, arg3) {
  return window['go']['main']['MCPAggregateWrapper']['UpdateMCPServerInstallation'](arg1, arg2, arg3);
}

export function UpdateProtectedMCPServerInstallation(arg1, arg2, arg3) {
  return window['go']['main']['MCPAggregateWrapper']['UpdateProtectedMCPServerInstallation'](arg1, arg2, arg3);
}
