// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearMCPServerSecret(arg1, arg2) {
  return window['go']['main']['MCPAggregateWrapper']['ClearMCPServerSecret'](arg1, arg2);
}

export function CreateMCPServer(arg1) {
  return window['go']['main']['MCPAggregateWrapper']['CreateMCPServer'](arg1);
}

export function DeleteMCPPolicy(arg1, arg2) {
  return window['go']['main']['MCPAggregateWrapper']['DeleteMCPPolicy'](arg1, arg2);
}

export function DeleteMCPServer(arg1, arg2) {
  return window['go']['main']['MCPAggregateWrapper']['DeleteMCPServer'](arg1, arg2);
}

export function GetMCPServer(arg1) {
  return window['go']['main']['MCPAggregateWrapper']['GetMCPServer'](arg1);
}

export function GetMCPServersForRuntimeServers(arg1) {
  return window['go']['main']['MCPAggregateWrapper']['GetMCPServersForRuntimeServers'](arg1);
}

export function ListMCPCollectionServers(arg1) {
  return window['go']['main']['MCPAggregateWrapper']['ListMCPCollectionServers'](arg1);
}

export function SaveMCPPolicy(arg1) {
  return window['go']['main']['MCPAggregateWrapper']['SaveMCPPolicy'](arg1);
}

export function SaveMCPServerSettings(arg1, arg2, arg3) {
  return window['go']['main']['MCPAggregateWrapper']['SaveMCPServerSettings'](arg1, arg2, arg3);
}

export function SetMCPServerSecret(arg1, arg2, arg3) {
  return window['go']['main']['MCPAggregateWrapper']['SetMCPServerSecret'](arg1, arg2, arg3);
}

export function UpdateMCPServer(arg1) {
  return window['go']['main']['MCPAggregateWrapper']['UpdateMCPServer'](arg1);
}
