// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';
import {conversation} from '../models';
import {main} from '../models';
import {auth} from '../models';

export function CancelPendingMCPOAuthAuthorization(arg1:server.ServerID):Promise<boolean>;

export function CompleteMCPArgument(arg1:server.ServerID,arg2:server.MCPCompleteArgumentRequestBody):Promise<server.MCPCompletionResult>;

export function ConnectMCPServer(arg1:server.ServerID):Promise<server.MCPServerRuntimeSnapshot>;

export function DisconnectMCPServer(arg1:server.ServerID):Promise<void>;

export function EvaluateMCPToolCall(arg1:server.ServerID,arg2:server.InvokeMCPToolRequestBody):Promise<server.MCPApprovalEvaluation>;

export function EvaluateMappedMCPToolCall(arg1:conversation.MCPProviderToolMapping,arg2:server.InvokeMCPToolRequestBody):Promise<server.MCPApprovalEvaluation>;

export function GetMCPGlobalSettings():Promise<main.MCPGlobalSettingsView>;

export function GetMCPPrompt(arg1:server.ServerID,arg2:string,arg3:Record<string, string>):Promise<server.MCPGetPromptResponseBody>;

export function GetMCPServerStatus(arg1:server.ServerID):Promise<server.MCPServerRuntimeSnapshot>;

export function InvokeMCPTool(arg1:server.ServerID,arg2:server.InvokeMCPToolRequestBody):Promise<server.InvokeMCPToolResponseBody>;

export function InvokeMappedMCPTool(arg1:conversation.MCPProviderToolMapping,arg2:server.InvokeMCPToolRequestBody):Promise<server.InvokeMCPToolResponseBody>;

export function ListMCPServerPrompts(arg1:server.ServerID):Promise<Array<server.MCPPromptRef>>;

export function ListMCPServerPromptsPage(arg1:server.ServerID,arg2:number,arg3:string):Promise<Array<server.MCPPromptRef>>;

export function ListMCPServerResourceTemplates(arg1:server.ServerID):Promise<Array<server.MCPResourceTemplateRef>>;

export function ListMCPServerResourceTemplatesPage(arg1:server.ServerID,arg2:number,arg3:string):Promise<Array<server.MCPResourceTemplateRef>>;

export function ListMCPServerResources(arg1:server.ServerID):Promise<Array<server.MCPResourceRef>>;

export function ListMCPServerResourcesPage(arg1:server.ServerID,arg2:number,arg3:string):Promise<Array<server.MCPResourceRef>>;

export function ListMCPServerTools(arg1:server.ServerID):Promise<Array<server.MCPToolCapability>>;

export function ListMCPServerToolsPage(arg1:server.ServerID,arg2:number,arg3:string):Promise<Array<server.MCPToolCapability>>;

export function ListPendingMCPOAuthAuthorizations():Promise<Array<auth.MCPOAuthAuthorization>>;

export function ReadMCPResource(arg1:server.ServerID,arg2:string):Promise<server.MCPReadResourceResponseBody>;

export function RefreshMCPServer(arg1:server.ServerID):Promise<server.MCPServerRuntimeSnapshot>;

export function ResolveMCPApproval(arg1:string,arg2:server.MCPApprovalResolution):Promise<server.MCPApprovalResolutionResult>;

export function StartMCPServerConnect(arg1:server.ServerID):Promise<server.MCPServerRuntimeSnapshot>;

export function UpdateMCPGlobalSettings(arg1:number,arg2:auth.MCPAuthSettings):Promise<number>;
