// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPendingMCPOAuthAuthorization(arg1) {
  return window['go']['main']['MCPRuntimeWrapper']['CancelPendingMCPOAuthAuthorization'](arg1);
}

export function CompleteMCPArgument(arg1, arg2) {
  return window['go']['main']['MCPRuntimeWrapper']['CompleteMCPArgument'](arg1, arg2);
}

export function ConnectMCPServer(arg1) {
  return window['go']['main']['MCPRuntimeWrapper']['ConnectMCPServer'](arg1);
}

export function DisconnectMCPServer(arg1) {
  return window['go']['main']['MCPRuntimeWrapper']['DisconnectMCPServer'](arg1);
}

export function EvaluateMCPToolCall(arg1, arg2) {
  return window['go']['main']['MCPRuntimeWrapper']['EvaluateMCPToolCall'](arg1, arg2);
}

export function EvaluateMappedMCPToolCall(arg1, arg2) {
  return window['go']['main']['MCPRuntimeWrapper']['EvaluateMappedMCPToolCall'](arg1, arg2);
}

export function GetMCPGlobalSettings() {
  return window['go']['main']['MCPRuntimeWrapper']['GetMCPGlobalSettings']();
}

export function GetMCPPrompt(arg1, arg2, arg3) {
  return window['go']['main']['MCPRuntimeWrapper']['GetMCPPrompt'](arg1, arg2, arg3);
}

export function GetMCPServerStatus(arg1) {
  return window['go']['main']['MCPRuntimeWrapper']['GetMCPServerStatus'](arg1);
}

export function InvokeMCPTool(arg1, arg2) {
  return window['go']['main']['MCPRuntimeWrapper']['InvokeMCPTool'](arg1, arg2);
}

export function InvokeMappedMCPTool(arg1, arg2) {
  return window['go']['main']['MCPRuntimeWrapper']['InvokeMappedMCPTool'](arg1, arg2);
}

export function ListMCPServerPrompts(arg1) {
  return window['go']['main']['MCPRuntimeWrapper']['ListMCPServerPrompts'](arg1);
}

export function ListMCPServerPromptsPage(arg1, arg2, arg3) {
  return window['go']['main']['MCPRuntimeWrapper']['ListMCPServerPromptsPage'](arg1, arg2, arg3);
}

export function ListMCPServerResourceTemplates(arg1) {
  return window['go']['main']['MCPRuntimeWrapper']['ListMCPServerResourceTemplates'](arg1);
}

export function ListMCPServerResourceTemplatesPage(arg1, arg2, arg3) {
  return window['go']['main']['MCPRuntimeWrapper']['ListMCPServerResourceTemplatesPage'](arg1, arg2, arg3);
}

export function ListMCPServerResources(arg1) {
  return window['go']['main']['MCPRuntimeWrapper']['ListMCPServerResources'](arg1);
}

export function ListMCPServerResourcesPage(arg1, arg2, arg3) {
  return window['go']['main']['MCPRuntimeWrapper']['ListMCPServerResourcesPage'](arg1, arg2, arg3);
}

export function ListMCPServerTools(arg1) {
  return window['go']['main']['MCPRuntimeWrapper']['ListMCPServerTools'](arg1);
}

export function ListMCPServerToolsPage(arg1, arg2, arg3) {
  return window['go']['main']['MCPRuntimeWrapper']['ListMCPServerToolsPage'](arg1, arg2, arg3);
}

export function ListPendingMCPOAuthAuthorizations() {
  return window['go']['main']['MCPRuntimeWrapper']['ListPendingMCPOAuthAuthorizations']();
}

export function ReadMCPResource(arg1, arg2) {
  return window['go']['main']['MCPRuntimeWrapper']['ReadMCPResource'](arg1, arg2);
}

export function RefreshMCPServer(arg1) {
  return window['go']['main']['MCPRuntimeWrapper']['RefreshMCPServer'](arg1);
}

export function ResolveMCPApproval(arg1, arg2) {
  return window['go']['main']['MCPRuntimeWrapper']['ResolveMCPApproval'](arg1, arg2);
}

export function StartMCPServerConnect(arg1) {
  return window['go']['main']['MCPRuntimeWrapper']['StartMCPServerConnect'](arg1);
}

export function UpdateMCPGlobalSettings(arg1, arg2) {
  return window['go']['main']['MCPRuntimeWrapper']['UpdateMCPGlobalSettings'](arg1, arg2);
}
