// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelMCPServerAuthorization(arg1) {
  return window['go']['main']['MCPRuntimeWrapper']['CancelMCPServerAuthorization'](arg1);
}

export function CheckMCPToolCall(arg1, arg2) {
  return window['go']['main']['MCPRuntimeWrapper']['CheckMCPToolCall'](arg1, arg2);
}

export function CompleteMCPArgument(arg1, arg2) {
  return window['go']['main']['MCPRuntimeWrapper']['CompleteMCPArgument'](arg1, arg2);
}

export function ConnectMCPServer(arg1) {
  return window['go']['main']['MCPRuntimeWrapper']['ConnectMCPServer'](arg1);
}

export function DisconnectMCPServer(arg1) {
  return window['go']['main']['MCPRuntimeWrapper']['DisconnectMCPServer'](arg1);
}

export function GetMCPPrompt(arg1, arg2, arg3) {
  return window['go']['main']['MCPRuntimeWrapper']['GetMCPPrompt'](arg1, arg2, arg3);
}

export function InvokeMCPTool(arg1, arg2) {
  return window['go']['main']['MCPRuntimeWrapper']['InvokeMCPTool'](arg1, arg2);
}

export function ListMCPServerPrompts(arg1, arg2, arg3) {
  return window['go']['main']['MCPRuntimeWrapper']['ListMCPServerPrompts'](arg1, arg2, arg3);
}

export function ListMCPServerResourceTemplates(arg1, arg2, arg3) {
  return window['go']['main']['MCPRuntimeWrapper']['ListMCPServerResourceTemplates'](arg1, arg2, arg3);
}

export function ListMCPServerResources(arg1, arg2, arg3) {
  return window['go']['main']['MCPRuntimeWrapper']['ListMCPServerResources'](arg1, arg2, arg3);
}

export function ListMCPServerTools(arg1, arg2, arg3) {
  return window['go']['main']['MCPRuntimeWrapper']['ListMCPServerTools'](arg1, arg2, arg3);
}

export function ReadMCPResource(arg1, arg2) {
  return window['go']['main']['MCPRuntimeWrapper']['ReadMCPResource'](arg1, arg2);
}

export function RefreshMCPServer(arg1) {
  return window['go']['main']['MCPRuntimeWrapper']['RefreshMCPServer'](arg1);
}

export function ResolveMCPToolApproval(arg1, arg2) {
  return window['go']['main']['MCPRuntimeWrapper']['ResolveMCPToolApproval'](arg1, arg2);
}
