// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';

export function CancelMCPServerAuthorization(arg1:server.ServerID):Promise<boolean>;

export function CheckMCPToolCall(arg1:server.ServerID,arg2:server.InvokeMCPToolRequestBody):Promise<server.MCPApprovalEvaluation>;

export function CompleteMCPArgument(arg1:server.ServerID,arg2:server.MCPCompleteArgumentRequestBody):Promise<server.MCPCompletionResult>;

export function ConnectMCPServer(arg1:server.ServerID):Promise<server.MCPServerRuntimeSnapshot>;

export function DisconnectMCPServer(arg1:server.ServerID):Promise<void>;

export function GetMCPPrompt(arg1:server.ServerID,arg2:string,arg3:Record<string, string>):Promise<server.MCPGetPromptResponseBody>;

export function InvokeMCPTool(arg1:server.ServerID,arg2:server.InvokeMCPToolRequestBody):Promise<server.InvokeMCPToolResponseBody>;

export function ListMCPServerPrompts(arg1:server.ServerID,arg2:number,arg3:string):Promise<server.MCPPromptPage>;

export function ListMCPServerResourceTemplates(arg1:server.ServerID,arg2:number,arg3:string):Promise<server.MCPResourceTemplatePage>;

export function ListMCPServerResources(arg1:server.ServerID,arg2:number,arg3:string):Promise<server.MCPResourcePage>;

export function ListMCPServerTools(arg1:server.ServerID,arg2:number,arg3:string):Promise<server.MCPToolCapabilityPage>;

export function ReadMCPResource(arg1:server.ServerID,arg2:string):Promise<server.MCPReadResourceResponseBody>;

export function RefreshMCPServer(arg1:server.ServerID):Promise<server.MCPServerRuntimeSnapshot>;

export function ResolveMCPToolApproval(arg1:string,arg2:server.MCPApprovalResolution):Promise<server.MCPApprovalResolutionResult>;
