// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collection} from '../models';
import {consumerapi} from '../models';
import {artifact} from '../models';
import {root} from '../models';
import {resolve} from '../models';

export function AddMCPCollectionMember(arg1:collection.AddMemberRequest):Promise<collection.CollectionView>;

export function AttachMCPArtifactToCollection(arg1:collection.AddArtifactMemberRequest):Promise<collection.CollectionView>;

export function CreateMCPCollection(arg1:collection.CreateRequest):Promise<collection.CollectionView>;

export function CreateManagedMCP(arg1:consumerapi.ManagedMCPCreateRequest):Promise<consumerapi.ManagedMCPCreateResult>;

export function DeleteMCPCollection(arg1:collection.DeleteRequest):Promise<void>;

export function GetMCPCollection(arg1:artifact.ArtifactRef):Promise<collection.CollectionView>;

export function GetMCPPolicy(arg1:artifact.ArtifactRef):Promise<consumerapi.PolicyView>;

export function GetMCPServerInstallation(arg1:artifact.ArtifactRef):Promise<consumerapi.ServerInstallationView>;

export function ListMCPCollectionMemberships(arg1:artifact.ArtifactRef):Promise<Array<collection.ArtifactMembershipView>>;

export function ListMCPCollections(arg1:root.RootID):Promise<Array<collection.CollectionView>>;

export function ListMCPCollectionsForManagement():Promise<Array<collection.CollectionView>>;

export function ListMCPPolicies(arg1:root.RootID):Promise<Array<artifact.Artifact>>;

export function ListMCPServers(arg1:root.RootID):Promise<Array<artifact.Artifact>>;

export function ListMCPServersForManagement():Promise<Array<artifact.Artifact>>;

export function PurgeManagedMCP(arg1:artifact.ArtifactRef,arg2:number):Promise<void>;

export function PurgeManagedMCPPolicy(arg1:artifact.ArtifactRef,arg2:number):Promise<void>;

export function RemoveMCPCollectionMember(arg1:collection.RemoveMemberRequest):Promise<collection.CollectionView>;

export function ReplaceManagedMCP(arg1:consumerapi.ManagedMCPReplaceRequest):Promise<consumerapi.ManagedMCPReplaceResult>;

export function ResolveMCPArtifactCapabilities(arg1:artifact.ArtifactRef):Promise<resolve.CapabilityPlan>;

export function ResolveMCPCollection(arg1:artifact.ArtifactRef):Promise<collection.CollectionCapabilityPlan>;

export function SetMCPCollectionEnabled(arg1:artifact.ArtifactRef,arg2:number,arg3:boolean):Promise<collection.CollectionView>;

export function SetMCPPolicyEnabled(arg1:artifact.ArtifactRef,arg2:number,arg3:boolean):Promise<artifact.Artifact>;

export function SetMCPServerEnabled(arg1:artifact.ArtifactRef,arg2:number,arg3:boolean):Promise<artifact.Artifact>;

export function UpdateMCPCollection(arg1:collection.UpdateRequest):Promise<collection.CollectionView>;

export function UpsertManagedMCPPolicy(arg1:consumerapi.ManagedMCPPolicyUpsertRequest):Promise<consumerapi.ManagedMCPPolicyUpsertResult>;
