// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugin} from '../models';
import {model} from '../models';
import {consumerapi} from '../models';
import {main} from '../models';
import {auth} from '../models';

export function AddMCPCollectionMember(arg1:plugin.AddMemberRequest):Promise<plugin.CollectionView>;

export function AddMCPServerToCollection(arg1:plugin.AddArtifactMemberRequest):Promise<plugin.CollectionView>;

export function CreateMCPCollection(arg1:plugin.CreateRequest):Promise<plugin.CollectionView>;

export function DeleteMCPCollection(arg1:plugin.DeleteRequest):Promise<void>;

export function GetMCPCollection(arg1:model.ArtifactRef):Promise<plugin.CollectionView>;

export function GetMCPPolicy(arg1:model.ArtifactRef):Promise<consumerapi.PolicyView>;

export function GetMCPServerSecrets(arg1:model.ArtifactRef):Promise<consumerapi.ServerSecretsView>;

export function GetMCPSettings():Promise<main.MCPSettingsView>;

export function ListMCPCollectionMemberships(arg1:model.ArtifactRef):Promise<Array<plugin.ArtifactMembershipView>>;

export function ListMCPCollections(arg1:model.RootID):Promise<Array<plugin.ListItem>>;

export function ListMCPCollectionsPage(arg1:number,arg2:string):Promise<consumerapi.CollectionPage>;

export function ListMCPPolicies(arg1:model.RootID):Promise<Array<consumerapi.PolicyListItem>>;

export function ListMCPServers(arg1:model.RootID):Promise<Array<consumerapi.ServerListItem>>;

export function ListMCPServersPage(arg1:number,arg2:string):Promise<consumerapi.ServerPage>;

export function RemoveMCPCollectionMember(arg1:plugin.RemoveMemberRequest):Promise<plugin.CollectionView>;

export function SaveMCPSettings(arg1:number,arg2:auth.MCPAuthSettings):Promise<main.MCPSettingsView>;

export function SetMCPCollectionEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<plugin.CollectionView>;

export function UpdateMCPCollection(arg1:plugin.UpdateRequest):Promise<plugin.CollectionView>;
