// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPCollectionMember(arg1) {
  return window['go']['main']['MCPStoreWrapper']['AddMCPCollectionMember'](arg1);
}

export function AttachMCPArtifactToCollection(arg1) {
  return window['go']['main']['MCPStoreWrapper']['AttachMCPArtifactToCollection'](arg1);
}

export function CreateMCPCollection(arg1) {
  return window['go']['main']['MCPStoreWrapper']['CreateMCPCollection'](arg1);
}

export function CreateManagedMCP(arg1) {
  return window['go']['main']['MCPStoreWrapper']['CreateManagedMCP'](arg1);
}

export function DeleteMCPCollection(arg1) {
  return window['go']['main']['MCPStoreWrapper']['DeleteMCPCollection'](arg1);
}

export function GetMCPCollection(arg1) {
  return window['go']['main']['MCPStoreWrapper']['GetMCPCollection'](arg1);
}

export function GetMCPPolicy(arg1) {
  return window['go']['main']['MCPStoreWrapper']['GetMCPPolicy'](arg1);
}

export function GetMCPServerInstallation(arg1) {
  return window['go']['main']['MCPStoreWrapper']['GetMCPServerInstallation'](arg1);
}

export function ListMCPCollectionMemberships(arg1) {
  return window['go']['main']['MCPStoreWrapper']['ListMCPCollectionMemberships'](arg1);
}

export function ListMCPCollections(arg1) {
  return window['go']['main']['MCPStoreWrapper']['ListMCPCollections'](arg1);
}

export function ListMCPCollectionsForManagement() {
  return window['go']['main']['MCPStoreWrapper']['ListMCPCollectionsForManagement']();
}

export function ListMCPPolicies(arg1) {
  return window['go']['main']['MCPStoreWrapper']['ListMCPPolicies'](arg1);
}

export function ListMCPServers(arg1) {
  return window['go']['main']['MCPStoreWrapper']['ListMCPServers'](arg1);
}

export function ListMCPServersForManagement() {
  return window['go']['main']['MCPStoreWrapper']['ListMCPServersForManagement']();
}

export function PurgeManagedMCP(arg1, arg2) {
  return window['go']['main']['MCPStoreWrapper']['PurgeManagedMCP'](arg1, arg2);
}

export function PurgeManagedMCPPolicy(arg1, arg2) {
  return window['go']['main']['MCPStoreWrapper']['PurgeManagedMCPPolicy'](arg1, arg2);
}

export function RemoveMCPCollectionMember(arg1) {
  return window['go']['main']['MCPStoreWrapper']['RemoveMCPCollectionMember'](arg1);
}

export function ReplaceManagedMCP(arg1) {
  return window['go']['main']['MCPStoreWrapper']['ReplaceManagedMCP'](arg1);
}

export function ResolveMCPArtifactCapabilities(arg1) {
  return window['go']['main']['MCPStoreWrapper']['ResolveMCPArtifactCapabilities'](arg1);
}

export function ResolveMCPCollection(arg1) {
  return window['go']['main']['MCPStoreWrapper']['ResolveMCPCollection'](arg1);
}

export function SetMCPCollectionEnabled(arg1, arg2, arg3) {
  return window['go']['main']['MCPStoreWrapper']['SetMCPCollectionEnabled'](arg1, arg2, arg3);
}

export function SetMCPPolicyEnabled(arg1, arg2, arg3) {
  return window['go']['main']['MCPStoreWrapper']['SetMCPPolicyEnabled'](arg1, arg2, arg3);
}

export function SetMCPServerEnabled(arg1, arg2, arg3) {
  return window['go']['main']['MCPStoreWrapper']['SetMCPServerEnabled'](arg1, arg2, arg3);
}

export function UpdateMCPCollection(arg1) {
  return window['go']['main']['MCPStoreWrapper']['UpdateMCPCollection'](arg1);
}

export function UpsertManagedMCPPolicy(arg1) {
  return window['go']['main']['MCPStoreWrapper']['UpsertManagedMCPPolicy'](arg1);
}
