// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugin} from '../models';
import {model} from '../models';
import {mcp} from '../models';
import {main} from '../models';
import {auth} from '../models';

export function AddMCPPluginMember(arg1:plugin.AddMemberRequest):Promise<plugin.PluginView>;

export function AddMCPServerToPlugin(arg1:plugin.AddArtifactMemberRequest):Promise<plugin.PluginView>;

export function CreateMCPPlugin(arg1:plugin.CreateRequest):Promise<plugin.PluginView>;

export function DeleteMCPPlugin(arg1:plugin.DeleteRequest):Promise<void>;

export function GetMCPPlugin(arg1:model.ArtifactRef):Promise<plugin.PluginView>;

export function GetMCPPolicy(arg1:model.ArtifactRef):Promise<mcp.PolicyView>;

export function GetMCPServerSecrets(arg1:model.ArtifactRef):Promise<mcp.ServerSecretsView>;

export function GetMCPSettings():Promise<main.MCPSettingsView>;

export function ListMCPPluginMemberships(arg1:model.ArtifactRef):Promise<Array<plugin.ArtifactMembershipView>>;

export function ListMCPPlugins(arg1:model.RootID):Promise<Array<plugin.ListItem>>;

export function ListMCPPluginsPage(arg1:number,arg2:string):Promise<mcp.PluginPage>;

export function ListMCPPolicies(arg1:model.RootID):Promise<Array<mcp.PolicyListItem>>;

export function ListMCPServers(arg1:model.RootID):Promise<Array<mcp.ServerListItem>>;

export function ListMCPServersPage(arg1:number,arg2:string):Promise<mcp.ServerPage>;

export function RemoveMCPPluginMember(arg1:plugin.RemoveMemberRequest):Promise<plugin.PluginView>;

export function SaveMCPSettings(arg1:number,arg2:auth.MCPAuthSettings):Promise<main.MCPSettingsView>;

export function SetMCPPluginEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<plugin.PluginView>;

export function UpdateMCPPlugin(arg1:plugin.UpdateRequest):Promise<plugin.PluginView>;
