// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPPluginMember(arg1) {
  return window['go']['main']['MCPStoreWrapper']['AddMCPPluginMember'](arg1);
}

export function AddMCPServerToPlugin(arg1) {
  return window['go']['main']['MCPStoreWrapper']['AddMCPServerToPlugin'](arg1);
}

export function CreateMCPPlugin(arg1) {
  return window['go']['main']['MCPStoreWrapper']['CreateMCPPlugin'](arg1);
}

export function DeleteMCPPlugin(arg1) {
  return window['go']['main']['MCPStoreWrapper']['DeleteMCPPlugin'](arg1);
}

export function GetMCPPlugin(arg1) {
  return window['go']['main']['MCPStoreWrapper']['GetMCPPlugin'](arg1);
}

export function GetMCPPolicy(arg1) {
  return window['go']['main']['MCPStoreWrapper']['GetMCPPolicy'](arg1);
}

export function GetMCPServerSecrets(arg1) {
  return window['go']['main']['MCPStoreWrapper']['GetMCPServerSecrets'](arg1);
}

export function GetMCPSettings() {
  return window['go']['main']['MCPStoreWrapper']['GetMCPSettings']();
}

export function ListMCPPluginMemberships(arg1) {
  return window['go']['main']['MCPStoreWrapper']['ListMCPPluginMemberships'](arg1);
}

export function ListMCPPlugins(arg1) {
  return window['go']['main']['MCPStoreWrapper']['ListMCPPlugins'](arg1);
}

export function ListMCPPluginsPage(arg1, arg2) {
  return window['go']['main']['MCPStoreWrapper']['ListMCPPluginsPage'](arg1, arg2);
}

export function ListMCPPolicies(arg1) {
  return window['go']['main']['MCPStoreWrapper']['ListMCPPolicies'](arg1);
}

export function ListMCPServers(arg1) {
  return window['go']['main']['MCPStoreWrapper']['ListMCPServers'](arg1);
}

export function ListMCPServersPage(arg1, arg2) {
  return window['go']['main']['MCPStoreWrapper']['ListMCPServersPage'](arg1, arg2);
}

export function RemoveMCPPluginMember(arg1) {
  return window['go']['main']['MCPStoreWrapper']['RemoveMCPPluginMember'](arg1);
}

export function SaveMCPSettings(arg1, arg2) {
  return window['go']['main']['MCPStoreWrapper']['SaveMCPSettings'](arg1, arg2);
}

export function SetMCPPluginEnabled(arg1, arg2, arg3) {
  return window['go']['main']['MCPStoreWrapper']['SetMCPPluginEnabled'](arg1, arg2, arg3);
}

export function UpdateMCPPlugin(arg1) {
  return window['go']['main']['MCPStoreWrapper']['UpdateMCPPlugin'](arg1);
}
