// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function CompleteMCPArgument(arg1:spec.MCPCompleteArgumentRequest):Promise<spec.MCPCompletionResult>;

export function ConnectMCPServer(arg1:spec.ConnectMCPServerRequest):Promise<spec.ConnectMCPServerResponse>;

export function DeleteMCPServer(arg1:spec.DeleteMCPServerRequest):Promise<spec.DeleteMCPServerResponse>;

export function DisconnectMCPServer(arg1:spec.DisconnectMCPServerRequest):Promise<spec.DisconnectMCPServerResponse>;

export function EvaluateMCPToolCall(arg1:spec.EvaluateMCPToolCallRequest):Promise<spec.EvaluateMCPToolCallResponse>;

export function GetMCPPrompt(arg1:spec.MCPGetPromptRequest):Promise<spec.MCPGetPromptResponse>;

export function GetMCPServer(arg1:spec.GetMCPServerRequest):Promise<spec.GetMCPServerResponse>;

export function GetMCPServerStatus(arg1:spec.GetMCPServerStatusRequest):Promise<spec.GetMCPServerStatusResponse>;

export function InvokeMCPTool(arg1:spec.InvokeMCPToolRequest):Promise<spec.InvokeMCPToolResponse>;

export function ListMCPServerPrompts(arg1:spec.ListMCPServerPromptsRequest):Promise<spec.ListMCPServerPromptsResponse>;

export function ListMCPServerResourceTemplates(arg1:spec.ListMCPServerResourceTemplatesRequest):Promise<spec.ListMCPServerResourceTemplatesResponse>;

export function ListMCPServerResources(arg1:spec.ListMCPServerResourcesRequest):Promise<spec.ListMCPServerResourcesResponse>;

export function ListMCPServerTools(arg1:spec.ListMCPServerToolsRequest):Promise<spec.ListMCPServerToolsResponse>;

export function ListMCPServers(arg1:spec.ListMCPServersRequest):Promise<spec.ListMCPServersResponse>;

export function PatchMCPServerEnabled(arg1:spec.PatchMCPServerEnabledRequest):Promise<spec.PatchMCPServerEnabledResponse>;

export function PatchMCPServerPolicy(arg1:spec.PatchMCPServerPolicyRequest):Promise<spec.PatchMCPServerPolicyResponse>;

export function PutMCPServer(arg1:spec.PutMCPServerRequest):Promise<spec.PutMCPServerResponse>;

export function ReadMCPResource(arg1:spec.MCPReadResourceRequest):Promise<spec.MCPReadResourceResponse>;

export function RefreshMCPServer(arg1:spec.RefreshMCPServerRequest):Promise<spec.RefreshMCPServerResponse>;

export function ResolveMCPApproval(arg1:spec.ResolveMCPApprovalRequest):Promise<spec.ResolveMCPApprovalResponse>;
