// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPendingMCPOAuthAuthorization(arg1) {
  return window['go']['main']['MCPWrapper']['CancelPendingMCPOAuthAuthorization'](arg1);
}

export function CompleteMCPArgument(arg1) {
  return window['go']['main']['MCPWrapper']['CompleteMCPArgument'](arg1);
}

export function ConnectMCPServer(arg1) {
  return window['go']['main']['MCPWrapper']['ConnectMCPServer'](arg1);
}

export function DeleteMCPBundle(arg1) {
  return window['go']['main']['MCPWrapper']['DeleteMCPBundle'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['MCPWrapper']['DeleteMCPServer'](arg1);
}

export function DeleteMCPServerSecret(arg1) {
  return window['go']['main']['MCPWrapper']['DeleteMCPServerSecret'](arg1);
}

export function DisconnectMCPServer(arg1) {
  return window['go']['main']['MCPWrapper']['DisconnectMCPServer'](arg1);
}

export function EvaluateMCPToolCall(arg1) {
  return window['go']['main']['MCPWrapper']['EvaluateMCPToolCall'](arg1);
}

export function GetMCPPrompt(arg1) {
  return window['go']['main']['MCPWrapper']['GetMCPPrompt'](arg1);
}

export function GetMCPServer(arg1) {
  return window['go']['main']['MCPWrapper']['GetMCPServer'](arg1);
}

export function GetMCPServerAuthHealth(arg1) {
  return window['go']['main']['MCPWrapper']['GetMCPServerAuthHealth'](arg1);
}

export function GetMCPServerAuthStatus(arg1) {
  return window['go']['main']['MCPWrapper']['GetMCPServerAuthStatus'](arg1);
}

export function GetMCPServerStatus(arg1) {
  return window['go']['main']['MCPWrapper']['GetMCPServerStatus'](arg1);
}

export function InvokeMCPTool(arg1) {
  return window['go']['main']['MCPWrapper']['InvokeMCPTool'](arg1);
}

export function ListMCPBundles(arg1) {
  return window['go']['main']['MCPWrapper']['ListMCPBundles'](arg1);
}

export function ListMCPServerPrompts(arg1) {
  return window['go']['main']['MCPWrapper']['ListMCPServerPrompts'](arg1);
}

export function ListMCPServerResourceTemplates(arg1) {
  return window['go']['main']['MCPWrapper']['ListMCPServerResourceTemplates'](arg1);
}

export function ListMCPServerResources(arg1) {
  return window['go']['main']['MCPWrapper']['ListMCPServerResources'](arg1);
}

export function ListMCPServerTools(arg1) {
  return window['go']['main']['MCPWrapper']['ListMCPServerTools'](arg1);
}

export function ListMCPServers(arg1) {
  return window['go']['main']['MCPWrapper']['ListMCPServers'](arg1);
}

export function ListPendingMCPOAuthAuthorizations(arg1) {
  return window['go']['main']['MCPWrapper']['ListPendingMCPOAuthAuthorizations'](arg1);
}

export function PatchMCPBundle(arg1) {
  return window['go']['main']['MCPWrapper']['PatchMCPBundle'](arg1);
}

export function PatchMCPServerEnabled(arg1) {
  return window['go']['main']['MCPWrapper']['PatchMCPServerEnabled'](arg1);
}

export function PatchMCPServerPolicy(arg1) {
  return window['go']['main']['MCPWrapper']['PatchMCPServerPolicy'](arg1);
}

export function PatchMCPServerSetup(arg1) {
  return window['go']['main']['MCPWrapper']['PatchMCPServerSetup'](arg1);
}

export function PatchMCPSettings(arg1) {
  return window['go']['main']['MCPWrapper']['PatchMCPSettings'](arg1);
}

export function PutMCPBundle(arg1) {
  return window['go']['main']['MCPWrapper']['PutMCPBundle'](arg1);
}

export function PutMCPServer(arg1) {
  return window['go']['main']['MCPWrapper']['PutMCPServer'](arg1);
}

export function PutMCPServerSecret(arg1) {
  return window['go']['main']['MCPWrapper']['PutMCPServerSecret'](arg1);
}

export function ReadMCPResource(arg1) {
  return window['go']['main']['MCPWrapper']['ReadMCPResource'](arg1);
}

export function RefreshMCPServer(arg1) {
  return window['go']['main']['MCPWrapper']['RefreshMCPServer'](arg1);
}

export function ResolveMCPApproval(arg1) {
  return window['go']['main']['MCPWrapper']['ResolveMCPApproval'](arg1);
}
