// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {artifact} from '../models';
import {runtime} from '../models';
import {mcpbundle} from '../models';
import {secret} from '../models';
import {collection} from '../models';
import {main} from '../models';
import {auth} from '../models';
import {server} from '../models';
import {basespec} from '../models';

export function CancelPendingMCPOAuthAuthorization(arg1:artifact.ArtifactRef):Promise<boolean>;

export function CompleteMCPArgument(arg1:artifact.ArtifactRef,arg2:runtime.MCPCompleteArgumentRequestBody):Promise<runtime.MCPCompletionResult>;

export function ConnectMCPServer(arg1:artifact.ArtifactRef):Promise<runtime.MCPServerRuntimeSnapshot>;

export function CreateMCPBundle(arg1:mcpbundle.CreateRequest):Promise<mcpbundle.Bundle>;

export function DeleteMCPServerSecret(arg1:artifact.ArtifactRef,arg2:secret.MCPSecretKind,arg3:string):Promise<void>;

export function DisconnectMCPServer(arg1:artifact.ArtifactRef):Promise<void>;

export function EvaluateMCPToolCall(arg1:artifact.ArtifactRef,arg2:runtime.InvokeMCPToolRequestBody):Promise<runtime.MCPApprovalEvaluation>;

export function EvaluateMappedMCPToolCall(arg1:runtime.MCPProviderToolMapping,arg2:runtime.InvokeMCPToolRequestBody):Promise<runtime.MCPApprovalEvaluation>;

export function GetMCPBundle(arg1:collection.CollectionRef):Promise<mcpbundle.Bundle>;

export function GetMCPBundleDocument(arg1:collection.CollectionRef):Promise<mcpbundle.BundleDocument>;

export function GetMCPBundleInstallation(arg1:collection.CollectionRef):Promise<mcpbundle.BundleInstallationView>;

export function GetMCPGlobalSettings():Promise<main.MCPGlobalSettingsView>;

export function GetMCPPrompt(arg1:artifact.ArtifactRef,arg2:string,arg3:Record<string, string>):Promise<runtime.MCPGetPromptResponseBody>;

export function GetMCPServerAuthHealth(arg1:artifact.ArtifactRef):Promise<auth.MCPAuthHealth>;

export function GetMCPServerInstallation(arg1:artifact.ArtifactRef):Promise<mcpbundle.ServerInstallationView>;

export function GetMCPServerStatus(arg1:artifact.ArtifactRef):Promise<runtime.MCPServerRuntimeSnapshot>;

export function InspectMCPPolicy(arg1:artifact.ArtifactRef):Promise<mcpbundle.PolicyView>;

export function InspectMCPServer(arg1:artifact.ArtifactRef):Promise<server.Resolved>;

export function InvokeMCPTool(arg1:artifact.ArtifactRef,arg2:runtime.InvokeMCPToolRequestBody):Promise<runtime.InvokeMCPToolResponseBody>;

export function InvokeMappedMCPTool(arg1:runtime.MCPProviderToolMapping,arg2:runtime.InvokeMCPToolRequestBody):Promise<runtime.InvokeMCPToolResponseBody>;

export function ListMCPBundlePolicies(arg1:collection.CollectionRef):Promise<Array<artifact.Artifact>>;

export function ListMCPBundleServers(arg1:collection.CollectionRef):Promise<Array<artifact.Artifact>>;

export function ListMCPBundles(arg1:basespec.RootID):Promise<Array<mcpbundle.Bundle>>;

export function ListMCPServerPrompts(arg1:artifact.ArtifactRef):Promise<Array<runtime.MCPPromptRef>>;

export function ListMCPServerResourceTemplates(arg1:artifact.ArtifactRef):Promise<Array<runtime.MCPResourceTemplateRef>>;

export function ListMCPServerResources(arg1:artifact.ArtifactRef):Promise<Array<runtime.MCPResourceRef>>;

export function ListMCPServerTools(arg1:artifact.ArtifactRef):Promise<Array<runtime.MCPToolCapability>>;

export function ListPendingMCPOAuthAuthorizations():Promise<Array<auth.MCPOAuthAuthorization>>;

export function PurgeMCPBundle(arg1:collection.CollectionRef,arg2:number):Promise<void>;

export function PutMCPServerSecret(arg1:artifact.ArtifactRef,arg2:secret.MCPSecretKind,arg3:string,arg4:string):Promise<main.MCPSecretWriteResult>;

export function ReadMCPResource(arg1:artifact.ArtifactRef,arg2:string):Promise<runtime.MCPReadResourceResponseBody>;

export function RefreshMCPBundle(arg1:collection.CollectionRef):Promise<mcpbundle.Bundle>;

export function RefreshMCPServer(arg1:artifact.ArtifactRef):Promise<runtime.MCPServerRuntimeSnapshot>;

export function ReplaceMCPBundleDocument(arg1:mcpbundle.ReplaceDocumentRequest):Promise<mcpbundle.Bundle>;

export function ResolveMCPApproval(arg1:string,arg2:runtime.MCPApprovalResolution):Promise<runtime.MCPApprovalToken>;

export function RetireMCPBundle(arg1:collection.CollectionRef,arg2:number):Promise<collection.Collection>;

export function UpdateMCPBundleEnabled(arg1:collection.CollectionRef,arg2:number,arg3:boolean):Promise<mcpbundle.Bundle>;

export function UpdateMCPGlobalSettings(arg1:number,arg2:auth.MCPAuthSettings):Promise<number>;

export function UpdateMCPServerInstallation(arg1:artifact.ArtifactRef,arg2:number,arg3:server.ServerData):Promise<artifact.Artifact>;

export function UpdateProtectedMCPBundleInstallation(arg1:collection.CollectionRef,arg2:number,arg3:boolean):Promise<void>;

export function UpdateProtectedMCPServerInstallation(arg1:artifact.ArtifactRef,arg2:number,arg3:boolean,arg4:server.ServerData):Promise<void>;
