// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {consumerapi} from '../models';
import {artifact} from '../models';
import {root} from '../models';

export function CreateModel(arg1:consumerapi.ManagedModelCreateRequest):Promise<consumerapi.ManagedModelCreateResult>;

export function DeleteModel(arg1:artifact.ArtifactRef,arg2:number):Promise<void>;

export function GetModel(arg1:artifact.ArtifactRef):Promise<consumerapi.ModelView>;

export function GetProvider(arg1:artifact.ArtifactRef):Promise<consumerapi.ProviderView>;

export function GetProviderAPIKeyStatus(arg1:artifact.ArtifactRef):Promise<consumerapi.ProviderAPIKeyStatus>;

export function ListModels(arg1:root.RootID):Promise<Array<consumerapi.ModelListItem>>;

export function ListProviders(arg1:root.RootID):Promise<Array<consumerapi.ProviderListItem>>;

export function ResetModelSettings(arg1:artifact.ArtifactRef,arg2:number,arg3:number):Promise<consumerapi.ModelView>;

export function SaveModelSettings(arg1:consumerapi.SaveModelSettingsRequest):Promise<consumerapi.ModelView>;

export function SetModelEnabled(arg1:artifact.ArtifactRef,arg2:number,arg3:boolean):Promise<artifact.Artifact>;

export function UpdateModel(arg1:consumerapi.ManagedModelReplaceRequest):Promise<consumerapi.ManagedModelReplaceResult>;
