// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {artifact} from '../models';
import {consumerapi} from '../models';

export function ClearDefaultProvider():Promise<void>;

export function ClearProviderAPIKey(arg1:artifact.ArtifactRef,arg2:number,arg3:number):Promise<consumerapi.ProviderAPIKeyStatus>;

export function CreateProvider(arg1:consumerapi.ManagedProviderCreateRequest):Promise<consumerapi.ManagedProviderCreateResult>;

export function DeleteProvider(arg1:artifact.ArtifactRef,arg2:number):Promise<void>;

export function GetDefaultProvider():Promise<artifact.ArtifactRef>;

export function ResetProviderSettings(arg1:artifact.ArtifactRef,arg2:number,arg3:number):Promise<consumerapi.ProviderView>;

export function SaveProviderSettings(arg1:consumerapi.SaveProviderSettingsRequest):Promise<consumerapi.ProviderView>;

export function SetDefaultProvider(arg1:artifact.ArtifactRef):Promise<void>;

export function SetProviderAPIKey(arg1:consumerapi.SetProviderAPIKeyRequest):Promise<consumerapi.ProviderAPIKeyStatus>;

export function SetProviderEnabled(arg1:artifact.ArtifactRef,arg2:number,arg3:boolean):Promise<artifact.Artifact>;

export function UpdateProvider(arg1:consumerapi.ManagedProviderReplaceRequest):Promise<consumerapi.ManagedProviderReplaceResult>;
