// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateModel(arg1:model.ManagedModelCreateRequest):Promise<model.ManagedModelCreateResult>;

export function DeleteModel(arg1:model.ArtifactRef,arg2:number):Promise<void>;

export function GetModel(arg1:model.ArtifactRef):Promise<model.ModelView>;

export function GetProvider(arg1:model.ArtifactRef):Promise<model.ProviderView>;

export function GetProviderAPIKeyStatus(arg1:model.ArtifactRef):Promise<model.ProviderAPIKeyStatus>;

export function ListModels(arg1:model.RootID):Promise<Array<model.ModelListItem>>;

export function ListProviders(arg1:model.RootID):Promise<Array<model.ProviderListItem>>;

export function ResetModelSettings(arg1:model.ArtifactRef,arg2:number,arg3:number):Promise<model.ModelView>;

export function SaveModelSettings(arg1:model.SaveModelSettingsRequest):Promise<model.ModelView>;

export function SetModelEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<model.Artifact>;

export function UpdateModel(arg1:model.ManagedModelReplaceRequest):Promise<model.ManagedModelReplaceResult>;
