// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ClearDefaultProvider():Promise<void>;

export function ClearProviderAPIKey(arg1:model.ArtifactRef,arg2:number,arg3:number):Promise<model.ProviderAPIKeyStatus>;

export function CreateProvider(arg1:model.ManagedProviderCreateRequest):Promise<model.ManagedProviderCreateResult>;

export function DeleteProvider(arg1:model.ArtifactRef,arg2:number):Promise<void>;

export function GetDefaultProvider():Promise<model.ArtifactRef>;

export function ResetProviderSettings(arg1:model.ArtifactRef,arg2:number,arg3:number):Promise<model.ProviderView>;

export function SaveProviderSettings(arg1:model.SaveProviderSettingsRequest):Promise<model.ProviderView>;

export function SetDefaultProvider(arg1:model.ArtifactRef):Promise<void>;

export function SetProviderAPIKey(arg1:model.SetProviderAPIKeyRequest):Promise<model.ProviderAPIKeyStatus>;

export function SetProviderEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<model.Artifact>;

export function UpdateProvider(arg1:model.ManagedProviderReplaceRequest):Promise<model.ManagedProviderReplaceResult>;
