// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateModel(arg1) {
  return window['go']['main']['ModelStoreWrapper']['CreateModel'](arg1);
}

export function DeleteModel(arg1, arg2) {
  return window['go']['main']['ModelStoreWrapper']['DeleteModel'](arg1, arg2);
}

export function GetModel(arg1) {
  return window['go']['main']['ModelStoreWrapper']['GetModel'](arg1);
}

export function GetProvider(arg1) {
  return window['go']['main']['ModelStoreWrapper']['GetProvider'](arg1);
}

export function GetProviderAPIKeyStatus(arg1) {
  return window['go']['main']['ModelStoreWrapper']['GetProviderAPIKeyStatus'](arg1);
}

export function ListModels(arg1) {
  return window['go']['main']['ModelStoreWrapper']['ListModels'](arg1);
}

export function ListProviders(arg1) {
  return window['go']['main']['ModelStoreWrapper']['ListProviders'](arg1);
}

export function ResetModelSettings(arg1, arg2, arg3) {
  return window['go']['main']['ModelStoreWrapper']['ResetModelSettings'](arg1, arg2, arg3);
}

export function SaveModelSettings(arg1) {
  return window['go']['main']['ModelStoreWrapper']['SaveModelSettings'](arg1);
}

export function SetModelEnabled(arg1, arg2, arg3) {
  return window['go']['main']['ModelStoreWrapper']['SetModelEnabled'](arg1, arg2, arg3);
}

export function UpdateModel(arg1) {
  return window['go']['main']['ModelStoreWrapper']['UpdateModel'](arg1);
}
