// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDefaultProvider() {
  return window['go']['main']['ModelAggregateWrapper']['ClearDefaultProvider']();
}

export function ClearProviderAPIKey(arg1, arg2, arg3) {
  return window['go']['main']['ModelAggregateWrapper']['ClearProviderAPIKey'](arg1, arg2, arg3);
}

export function CreateProvider(arg1) {
  return window['go']['main']['ModelAggregateWrapper']['CreateProvider'](arg1);
}

export function DeleteProvider(arg1, arg2) {
  return window['go']['main']['ModelAggregateWrapper']['DeleteProvider'](arg1, arg2);
}

export function GetDefaultProvider() {
  return window['go']['main']['ModelAggregateWrapper']['GetDefaultProvider']();
}

export function ResetProviderSettings(arg1, arg2, arg3) {
  return window['go']['main']['ModelAggregateWrapper']['ResetProviderSettings'](arg1, arg2, arg3);
}

export function SaveProviderSettings(arg1) {
  return window['go']['main']['ModelAggregateWrapper']['SaveProviderSettings'](arg1);
}

export function SetDefaultProvider(arg1) {
  return window['go']['main']['ModelAggregateWrapper']['SetDefaultProvider'](arg1);
}

export function SetProviderAPIKey(arg1) {
  return window['go']['main']['ModelAggregateWrapper']['SetProviderAPIKey'](arg1);
}

export function SetProviderEnabled(arg1, arg2, arg3) {
  return window['go']['main']['ModelAggregateWrapper']['SetProviderEnabled'](arg1, arg2, arg3);
}

export function UpdateProvider(arg1) {
  return window['go']['main']['ModelAggregateWrapper']['UpdateProvider'](arg1);
}
