// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultModelProvider() {
  return window['go']['main']['ModelAggregateWrapper']['GetDefaultModelProvider']();
}

export function GetModelProviderDefaultModel(arg1) {
  return window['go']['main']['ModelAggregateWrapper']['GetModelProviderDefaultModel'](arg1);
}

export function SetDefaultModelProvider(arg1) {
  return window['go']['main']['ModelAggregateWrapper']['SetDefaultModelProvider'](arg1);
}
