// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateManagedModel(arg1) {
  return window['go']['main']['ModelStoreWrapper']['CreateManagedModel'](arg1);
}

export function CreateModelProvider(arg1) {
  return window['go']['main']['ModelStoreWrapper']['CreateModelProvider'](arg1);
}

export function DeleteManagedModel(arg1, arg2) {
  return window['go']['main']['ModelStoreWrapper']['DeleteManagedModel'](arg1, arg2);
}

export function DeleteModelProvider(arg1, arg2) {
  return window['go']['main']['ModelStoreWrapper']['DeleteModelProvider'](arg1, arg2);
}

export function GetModel(arg1) {
  return window['go']['main']['ModelStoreWrapper']['GetModel'](arg1);
}

export function GetModelProvider(arg1) {
  return window['go']['main']['ModelStoreWrapper']['GetModelProvider'](arg1);
}

export function ListModelProviders(arg1) {
  return window['go']['main']['ModelStoreWrapper']['ListModelProviders'](arg1);
}

export function ListModels(arg1) {
  return window['go']['main']['ModelStoreWrapper']['ListModels'](arg1);
}

export function ReplaceManagedModel(arg1) {
  return window['go']['main']['ModelStoreWrapper']['ReplaceManagedModel'](arg1);
}

export function ReplaceModelProvider(arg1) {
  return window['go']['main']['ModelStoreWrapper']['ReplaceModelProvider'](arg1);
}

export function SetModelEnabled(arg1, arg2, arg3) {
  return window['go']['main']['ModelStoreWrapper']['SetModelEnabled'](arg1, arg2, arg3);
}

export function SetModelProviderCredential(arg1, arg2, arg3) {
  return window['go']['main']['ModelStoreWrapper']['SetModelProviderCredential'](arg1, arg2, arg3);
}

export function SetModelProviderEnabled(arg1, arg2, arg3) {
  return window['go']['main']['ModelStoreWrapper']['SetModelProviderEnabled'](arg1, arg2, arg3);
}
