// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function DeleteModelPreset(arg1:spec.DeleteModelPresetRequest):Promise<spec.DeleteModelPresetResponse>;

export function GetDefaultProvider(arg1:spec.GetDefaultProviderRequest):Promise<spec.GetDefaultProviderResponse>;

export function GetModelPreset(arg1:spec.GetModelPresetRequest):Promise<spec.GetModelPresetResponse>;

export function ListProviderPresets(arg1:spec.ListProviderPresetsRequest):Promise<spec.ListProviderPresetsResponse>;

export function PatchDefaultProvider(arg1:spec.PatchDefaultProviderRequest):Promise<spec.PatchDefaultProviderResponse>;

export function PatchModelPreset(arg1:spec.PatchModelPresetRequest):Promise<spec.PatchModelPresetResponse>;

export function PatchProviderPreset(arg1:spec.PatchProviderPresetRequest):Promise<spec.PatchProviderPresetResponse>;

export function PostModelPreset(arg1:spec.PostModelPresetRequest):Promise<spec.PostModelPresetResponse>;
