// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {artifact} from '../models';

export function GetDefaultModelProvider():Promise<artifact.ArtifactRef>;

export function GetModelProviderDefaultModel(arg1:artifact.ArtifactRef):Promise<artifact.ArtifactRef>;

export function SetDefaultModelProvider(arg1:artifact.ArtifactRef):Promise<void>;
