// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function GetAuthKey(arg1:spec.GetAuthKeyRequest):Promise<spec.GetAuthKeyResponse>;

export function GetSettings(arg1:spec.GetSettingsRequest):Promise<spec.GetSettingsResponse>;

export function SetAppTheme(arg1:spec.SetAppThemeRequest):Promise<spec.SetAppThemeResponse>;

export function SetDebugSettings(arg1:spec.SetDebugSettingsRequest):Promise<spec.SetDebugSettingsResponse>;
