// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {setting} from '../models';

export function GetSettings(arg1:setting.GetSettingsRequest):Promise<setting.GetSettingsResponse>;

export function SetAppTheme(arg1:setting.SetAppThemeRequest):Promise<setting.SetAppThemeResponse>;

export function SetDebugSettings(arg1:setting.SetDebugSettingsRequest):Promise<setting.SetDebugSettingsResponse>;
