// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {aggregate} from '../models';

export function DescribeArtifactSkill(arg1:model.ArtifactRef):Promise<aggregate.ArtifactSkillSummary>;

export function GetArtifactSkillsPrompt(arg1:aggregate.ArtifactSkillFilter):Promise<string>;

export function ListArtifactSkillRefs(arg1:aggregate.ArtifactSkillFilter):Promise<Array<model.ArtifactRef>>;

export function ResolveArtifactSkill(arg1:model.ArtifactRef):Promise<aggregate.ResolvedArtifactSkill>;

export function ResolveArtifactSkills(arg1:Array<model.ArtifactRef>):Promise<Array<aggregate.ResolvedArtifactSkill>>;
