// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collection} from '../models';
import {runtime} from '../models';

export function RuntimeCatalogIDForCollection(arg1:collection.CollectionRef):Promise<runtime.CatalogID>;
