// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugin} from '../models';
import {consumerapi} from '../models';
import {model} from '../models';
import {domain} from '../models';
import {composition} from '../models';

export function AddSkillCollectionMember(arg1:plugin.AddMemberRequest):Promise<plugin.CollectionView>;

export function AddSkillPath(arg1:consumerapi.SkillPathRegistration):Promise<consumerapi.SkillPathRegistrationResult>;

export function AttachSkillArtifactToCollection(arg1:plugin.AddArtifactMemberRequest):Promise<plugin.CollectionView>;

export function CreateManagedSkill(arg1:consumerapi.ManagedSkillCreateRequest):Promise<consumerapi.ManagedSkillCreateResult>;

export function CreateSkillCollection(arg1:plugin.CreateRequest):Promise<plugin.CollectionView>;

export function DeleteSkillCollection(arg1:plugin.DeleteRequest):Promise<void>;

export function GetManagedSkillDocument(arg1:model.ArtifactRef):Promise<domain.ManagedSkillDocument>;

export function GetSkill(arg1:model.ArtifactRef):Promise<model.Artifact>;

export function GetSkillCollection(arg1:model.ArtifactRef):Promise<plugin.CollectionView>;

export function ListSkillCollectionMemberships(arg1:model.ArtifactRef):Promise<Array<plugin.ArtifactMembershipView>>;

export function ListSkillCollections(arg1:model.RootID):Promise<Array<plugin.ListItem>>;

export function ListSkillCollectionsForManagement():Promise<Array<plugin.ListItem>>;

export function ListSkills(arg1:model.RootID):Promise<Array<consumerapi.SkillListItem>>;

export function ListSkillsForManagement():Promise<Array<consumerapi.SkillListItem>>;

export function PurgeSkill(arg1:model.ArtifactRef,arg2:number):Promise<void>;

export function RefreshSkillSource(arg1:model.RootID,arg2:model.SourceID):Promise<void>;

export function RegisterSkillDirectory(arg1:consumerapi.SkillDirectoryRegistration):Promise<model.Summary>;

export function RemoveSkillCollectionMember(arg1:plugin.RemoveMemberRequest):Promise<plugin.CollectionView>;

export function ReplaceManagedSkill(arg1:consumerapi.ManagedSkillReplaceRequest):Promise<consumerapi.ManagedSkillReplaceResult>;

export function ResolveSkillCapabilities(arg1:model.ArtifactRef):Promise<composition.CapabilityPlan>;

export function ResolveSkillCollection(arg1:model.ArtifactRef):Promise<plugin.CollectionCapabilityPlan>;

export function SetSkillCollectionEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<plugin.CollectionView>;

export function SetSkillEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<model.Artifact>;

export function UpdateSkillCollection(arg1:plugin.UpdateRequest):Promise<plugin.CollectionView>;
