// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {skill} from '../models';
import {plugin} from '../models';
import {model} from '../models';
import {source} from '../models';
import {composition} from '../models';

export function AddSkillPath(arg1:skill.SkillPathRegistration):Promise<skill.SkillPathRegistrationResult>;

export function AddSkillPluginMember(arg1:plugin.AddMemberRequest):Promise<plugin.PluginView>;

export function AttachSkillArtifactToPlugin(arg1:plugin.AddArtifactMemberRequest):Promise<plugin.PluginView>;

export function CreateManagedSkill(arg1:skill.ManagedSkillCreateRequest):Promise<skill.ManagedSkillCreateResult>;

export function CreateSkillPlugin(arg1:plugin.CreateRequest):Promise<plugin.PluginView>;

export function DeleteSkillPlugin(arg1:plugin.DeleteRequest):Promise<void>;

export function GetManagedSkillDocument(arg1:model.ArtifactRef):Promise<source.ManagedSkillDocument>;

export function GetSkill(arg1:model.ArtifactRef):Promise<model.Artifact>;

export function GetSkillPlugin(arg1:model.ArtifactRef):Promise<plugin.PluginView>;

export function ListSkillPluginMemberships(arg1:model.ArtifactRef):Promise<Array<plugin.ArtifactMembershipView>>;

export function ListSkillPlugins(arg1:model.RootID):Promise<Array<plugin.ListItem>>;

export function ListSkillPluginsForManagement():Promise<Array<plugin.ListItem>>;

export function ListSkills(arg1:model.RootID):Promise<Array<skill.SkillListItem>>;

export function ListSkillsForManagement():Promise<Array<skill.SkillListItem>>;

export function PurgeSkill(arg1:model.ArtifactRef,arg2:number):Promise<void>;

export function RefreshSkillSource(arg1:model.RootID,arg2:model.SourceID):Promise<void>;

export function RegisterSkillDirectory(arg1:skill.SkillDirectoryRegistration):Promise<model.Summary>;

export function RemoveSkillPluginMember(arg1:plugin.RemoveMemberRequest):Promise<plugin.PluginView>;

export function ReplaceManagedSkill(arg1:skill.ManagedSkillReplaceRequest):Promise<skill.ManagedSkillReplaceResult>;

export function ResolveSkillCapabilities(arg1:model.ArtifactRef):Promise<composition.CapabilityPlan>;

export function ResolveSkillPlugin(arg1:model.ArtifactRef):Promise<plugin.PluginCapabilityPlan>;

export function SetSkillEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<model.Artifact>;

export function SetSkillPluginEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<plugin.PluginView>;

export function UpdateSkillPlugin(arg1:plugin.UpdateRequest):Promise<plugin.PluginView>;
