// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSkillPath(arg1) {
  return window['go']['main']['SkillStoreWrapper']['AddSkillPath'](arg1);
}

export function AddSkillPluginMember(arg1) {
  return window['go']['main']['SkillStoreWrapper']['AddSkillPluginMember'](arg1);
}

export function AttachSkillArtifactToPlugin(arg1) {
  return window['go']['main']['SkillStoreWrapper']['AttachSkillArtifactToPlugin'](arg1);
}

export function CreateManagedSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['CreateManagedSkill'](arg1);
}

export function CreateSkillPlugin(arg1) {
  return window['go']['main']['SkillStoreWrapper']['CreateSkillPlugin'](arg1);
}

export function DeleteSkillPlugin(arg1) {
  return window['go']['main']['SkillStoreWrapper']['DeleteSkillPlugin'](arg1);
}

export function GetManagedSkillDocument(arg1) {
  return window['go']['main']['SkillStoreWrapper']['GetManagedSkillDocument'](arg1);
}

export function GetSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['GetSkill'](arg1);
}

export function GetSkillPlugin(arg1) {
  return window['go']['main']['SkillStoreWrapper']['GetSkillPlugin'](arg1);
}

export function ListSkillPluginMemberships(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ListSkillPluginMemberships'](arg1);
}

export function ListSkillPlugins(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ListSkillPlugins'](arg1);
}

export function ListSkillPluginsForManagement() {
  return window['go']['main']['SkillStoreWrapper']['ListSkillPluginsForManagement']();
}

export function ListSkills(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ListSkills'](arg1);
}

export function ListSkillsForManagement() {
  return window['go']['main']['SkillStoreWrapper']['ListSkillsForManagement']();
}

export function PurgeSkill(arg1, arg2) {
  return window['go']['main']['SkillStoreWrapper']['PurgeSkill'](arg1, arg2);
}

export function RefreshSkillSource(arg1, arg2) {
  return window['go']['main']['SkillStoreWrapper']['RefreshSkillSource'](arg1, arg2);
}

export function RegisterSkillDirectory(arg1) {
  return window['go']['main']['SkillStoreWrapper']['RegisterSkillDirectory'](arg1);
}

export function RemoveSkillPluginMember(arg1) {
  return window['go']['main']['SkillStoreWrapper']['RemoveSkillPluginMember'](arg1);
}

export function ReplaceManagedSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ReplaceManagedSkill'](arg1);
}

export function ResolveSkillCapabilities(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ResolveSkillCapabilities'](arg1);
}

export function ResolveSkillPlugin(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ResolveSkillPlugin'](arg1);
}

export function SetSkillEnabled(arg1, arg2, arg3) {
  return window['go']['main']['SkillStoreWrapper']['SetSkillEnabled'](arg1, arg2, arg3);
}

export function SetSkillPluginEnabled(arg1, arg2, arg3) {
  return window['go']['main']['SkillStoreWrapper']['SetSkillPluginEnabled'](arg1, arg2, arg3);
}

export function UpdateSkillPlugin(arg1) {
  return window['go']['main']['SkillStoreWrapper']['UpdateSkillPlugin'](arg1);
}
