// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';
import {skillruntime} from '../models';

export function DescribeArtifactSkill(arg1:model.ArtifactRef):Promise<main.ArtifactSkillSummary>;

export function GetArtifactSkillsPrompt(arg1:main.ArtifactSkillFilter):Promise<string>;

export function ListArtifactSkillRefs(arg1:main.ArtifactSkillFilter):Promise<Array<model.ArtifactRef>>;

export function ResolveArtifactSkill(arg1:model.ArtifactRef):Promise<skillruntime.ResolvedArtifactSkill>;

export function ResolveArtifactSkills(arg1:Array<model.ArtifactRef>):Promise<Array<skillruntime.ResolvedArtifactSkill>>;
