// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function Close():Promise<void>;

export function CloseSkillSession(arg1:spec.CloseSkillSessionRequest):Promise<spec.CloseSkillSessionResponse>;

export function CreateSkillSession(arg1:spec.CreateSkillSessionRequest):Promise<spec.CreateSkillSessionResponse>;

export function DeleteSkill(arg1:spec.DeleteSkillRequest):Promise<spec.DeleteSkillResponse>;

export function DeleteSkillBundle(arg1:spec.DeleteSkillBundleRequest):Promise<spec.DeleteSkillBundleResponse>;

export function GetSkill(arg1:spec.GetSkillRequest):Promise<spec.GetSkillResponse>;

export function GetSkillsPromptXML(arg1:spec.GetSkillsPromptXMLRequest):Promise<spec.GetSkillsPromptXMLResponse>;

export function ListRuntimeSkills(arg1:spec.ListRuntimeSkillsRequest):Promise<spec.ListRuntimeSkillsResponse>;

export function ListSkillBundles(arg1:spec.ListSkillBundlesRequest):Promise<spec.ListSkillBundlesResponse>;

export function ListSkills(arg1:spec.ListSkillsRequest):Promise<spec.ListSkillsResponse>;

export function PatchSkill(arg1:spec.PatchSkillRequest):Promise<spec.PatchSkillResponse>;

export function PatchSkillBundle(arg1:spec.PatchSkillBundleRequest):Promise<spec.PatchSkillBundleResponse>;

export function PutSkill(arg1:spec.PutSkillRequest):Promise<spec.PutSkillResponse>;

export function PutSkillBundle(arg1:spec.PutSkillBundleRequest):Promise<spec.PutSkillBundleResponse>;
