// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSkillSession(arg1) {
  return window['go']['main']['SkillRuntimeWrapper']['CloseSkillSession'](arg1);
}

export function CreateSkillSession(arg1) {
  return window['go']['main']['SkillRuntimeWrapper']['CreateSkillSession'](arg1);
}

export function GetSkillsPrompt(arg1) {
  return window['go']['main']['SkillRuntimeWrapper']['GetSkillsPrompt'](arg1);
}

export function InvokeSkillTool(arg1) {
  return window['go']['main']['SkillRuntimeWrapper']['InvokeSkillTool'](arg1);
}

export function ListSkills(arg1) {
  return window['go']['main']['SkillRuntimeWrapper']['ListSkills'](arg1);
}

export function RemoveSkillCatalog(arg1) {
  return window['go']['main']['SkillRuntimeWrapper']['RemoveSkillCatalog'](arg1);
}

export function RenderSkill(arg1) {
  return window['go']['main']['SkillRuntimeWrapper']['RenderSkill'](arg1);
}

export function SyncSkillCatalog(arg1) {
  return window['go']['main']['SkillRuntimeWrapper']['SyncSkillCatalog'](arg1);
}
