// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DescribeArtifactSkill(arg1) {
  return window['go']['main']['SkillAggregateWrapper']['DescribeArtifactSkill'](arg1);
}

export function GetArtifactSkillsPrompt(arg1) {
  return window['go']['main']['SkillAggregateWrapper']['GetArtifactSkillsPrompt'](arg1);
}

export function ListArtifactSkillRefs(arg1) {
  return window['go']['main']['SkillAggregateWrapper']['ListArtifactSkillRefs'](arg1);
}

export function ResolveArtifactSkill(arg1) {
  return window['go']['main']['SkillAggregateWrapper']['ResolveArtifactSkill'](arg1);
}
