// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['SkillStoreWrapper']['Close']();
}

export function DeleteSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['DeleteSkill'](arg1);
}

export function DeleteSkillBundle(arg1) {
  return window['go']['main']['SkillStoreWrapper']['DeleteSkillBundle'](arg1);
}

export function GetSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['GetSkill'](arg1);
}

export function ListSkillBundles(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ListSkillBundles'](arg1);
}

export function ListSkills(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ListSkills'](arg1);
}

export function PatchSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['PatchSkill'](arg1);
}

export function PatchSkillBundle(arg1) {
  return window['go']['main']['SkillStoreWrapper']['PatchSkillBundle'](arg1);
}

export function PutSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['PutSkill'](arg1);
}

export function PutSkillBundle(arg1) {
  return window['go']['main']['SkillStoreWrapper']['PutSkillBundle'](arg1);
}
