// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtime} from '../models';

export function CloseSkillSession(arg1:runtime.CloseSkillSessionRequest):Promise<runtime.CloseSkillSessionResponse>;

export function CreateSkillSession(arg1:runtime.CreateSkillSessionRequest):Promise<runtime.CreateSkillSessionResponse>;

export function GetSkillsPrompt(arg1:runtime.GetSkillsPromptRequest):Promise<runtime.GetSkillsPromptResponse>;

export function InvokeSkillTool(arg1:runtime.InvokeSkillToolRequest):Promise<runtime.InvokeSkillToolResponse>;

export function ListSkills(arg1:runtime.ListSkillsRequest):Promise<runtime.ListSkillsResponse>;

export function RenderSkill(arg1:runtime.RenderSkillRequest):Promise<runtime.RenderSkillResponse>;
