// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {skill} from '../models';

export function CloseSkillSession(arg1:skill.CloseSkillSessionRequest):Promise<skill.CloseSkillSessionResponse>;

export function CreateSkillSession(arg1:skill.CreateSkillSessionRequest):Promise<skill.CreateSkillSessionResponse>;

export function GetSkillsPrompt(arg1:skill.GetSkillsPromptRequest):Promise<skill.GetSkillsPromptResponse>;

export function InvokeSkillTool(arg1:skill.InvokeSkillToolRequest):Promise<skill.InvokeSkillToolResponse>;

export function ListSkills(arg1:skill.ListSkillsRequest):Promise<skill.ListSkillsResponse>;

export function RenderSkill(arg1:skill.RenderSkillRequest):Promise<skill.RenderSkillResponse>;
