// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSkillCollectionMember(arg1) {
  return window['go']['main']['SkillStoreWrapper']['AddSkillCollectionMember'](arg1);
}

export function AddSkillPath(arg1) {
  return window['go']['main']['SkillStoreWrapper']['AddSkillPath'](arg1);
}

export function AttachSkillArtifactToCollection(arg1) {
  return window['go']['main']['SkillStoreWrapper']['AttachSkillArtifactToCollection'](arg1);
}

export function CreateManagedSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['CreateManagedSkill'](arg1);
}

export function CreateSkillCollection(arg1) {
  return window['go']['main']['SkillStoreWrapper']['CreateSkillCollection'](arg1);
}

export function DeleteSkillCollection(arg1) {
  return window['go']['main']['SkillStoreWrapper']['DeleteSkillCollection'](arg1);
}

export function GetManagedSkillDocument(arg1) {
  return window['go']['main']['SkillStoreWrapper']['GetManagedSkillDocument'](arg1);
}

export function GetSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['GetSkill'](arg1);
}

export function GetSkillCollection(arg1) {
  return window['go']['main']['SkillStoreWrapper']['GetSkillCollection'](arg1);
}

export function ListSkillCollectionMemberships(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ListSkillCollectionMemberships'](arg1);
}

export function ListSkillCollections(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ListSkillCollections'](arg1);
}

export function ListSkillCollectionsForManagement() {
  return window['go']['main']['SkillStoreWrapper']['ListSkillCollectionsForManagement']();
}

export function ListSkills(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ListSkills'](arg1);
}

export function ListSkillsForManagement() {
  return window['go']['main']['SkillStoreWrapper']['ListSkillsForManagement']();
}

export function PurgeSkill(arg1, arg2) {
  return window['go']['main']['SkillStoreWrapper']['PurgeSkill'](arg1, arg2);
}

export function RefreshSkillSource(arg1, arg2) {
  return window['go']['main']['SkillStoreWrapper']['RefreshSkillSource'](arg1, arg2);
}

export function RegisterSkillDirectory(arg1) {
  return window['go']['main']['SkillStoreWrapper']['RegisterSkillDirectory'](arg1);
}

export function RemoveSkillCollectionMember(arg1) {
  return window['go']['main']['SkillStoreWrapper']['RemoveSkillCollectionMember'](arg1);
}

export function ReplaceManagedSkill(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ReplaceManagedSkill'](arg1);
}

export function ResolveSkillArtifactCapabilities(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ResolveSkillArtifactCapabilities'](arg1);
}

export function ResolveSkillCapabilities(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ResolveSkillCapabilities'](arg1);
}

export function ResolveSkillCollection(arg1) {
  return window['go']['main']['SkillStoreWrapper']['ResolveSkillCollection'](arg1);
}

export function SetSkillCollectionEnabled(arg1, arg2, arg3) {
  return window['go']['main']['SkillStoreWrapper']['SetSkillCollectionEnabled'](arg1, arg2, arg3);
}

export function SetSkillEnabled(arg1, arg2, arg3) {
  return window['go']['main']['SkillStoreWrapper']['SetSkillEnabled'](arg1, arg2, arg3);
}

export function UpdateSkillCollection(arg1) {
  return window['go']['main']['SkillStoreWrapper']['UpdateSkillCollection'](arg1);
}
