// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {text} from '../models';

export function MaterializeText(arg1:model.ArtifactRef):Promise<text.Materialization>;
