// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {tool} from '../models';
import {plugin} from '../models';
import {composition} from '../models';
import {llmtoolsutil} from '../models';

export function GetTool(arg1:model.ArtifactRef):Promise<tool.ToolView>;

export function GetToolPlugin(arg1:model.ArtifactRef):Promise<plugin.PluginView>;

export function InvokeGoToolTarget(arg1:composition.CapabilityTarget,arg2:string,arg3:number):Promise<llmtoolsutil.InvokeResponse>;

export function ListPluginTools(arg1:model.ArtifactRef):Promise<Array<tool.ToolListItem>>;

export function ListToolPlugins():Promise<Array<plugin.ListItem>>;

export function MapToolTarget(arg1:model.ArtifactRef):Promise<composition.CapabilityTarget>;

export function ResolveToolTarget(arg1:composition.CapabilityTarget):Promise<tool.ResolvedToolView>;

export function SetToolEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<tool.ToolView>;

export function SetToolPluginEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<plugin.PluginView>;
