// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InvokeTool(arg1) {
  return window['go']['main']['ToolRuntimeWrapper']['InvokeTool'](arg1);
}
