// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {aggregate} from '../models';
import {spec} from '../models';
import {main} from '../models';
import {runtime} from '../models';
import {artifact} from '../models';
import {resolve} from '../models';
import {consumerapi} from '../models';

export function HydrateInferenceToolChoice(arg1:aggregate.ToolSelection):Promise<spec.ToolChoice>;

export function InvokeMappedTool(arg1:main.ToolAggregateInvokeRequest):Promise<runtime.InvokeResponse>;

export function MapToolTarget(arg1:artifact.ArtifactRef):Promise<resolve.MappedTarget>;

export function ResolveMappedTool(arg1:resolve.MappedTarget):Promise<consumerapi.ResolvedToolView>;
