// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {consumerapi} from '../models';
import {plugin} from '../models';

export function GetTool(arg1:model.ArtifactRef):Promise<consumerapi.ToolView>;

export function GetToolCollection(arg1:model.ArtifactRef):Promise<plugin.CollectionView>;

export function ListCollectionTools(arg1:model.ArtifactRef):Promise<Array<consumerapi.ToolListItem>>;

export function ListToolCollections():Promise<Array<plugin.ListItem>>;

export function SetToolCollectionEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<plugin.CollectionView>;

export function SetToolEnabled(arg1:model.ArtifactRef,arg2:number,arg3:boolean):Promise<consumerapi.ToolView>;
