// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTool(arg1) {
  return window['go']['main']['ToolStoreWrapper']['GetTool'](arg1);
}

export function GetToolPlugin(arg1) {
  return window['go']['main']['ToolStoreWrapper']['GetToolPlugin'](arg1);
}

export function InvokeGoToolTarget(arg1, arg2, arg3) {
  return window['go']['main']['ToolStoreWrapper']['InvokeGoToolTarget'](arg1, arg2, arg3);
}

export function ListPluginTools(arg1) {
  return window['go']['main']['ToolStoreWrapper']['ListPluginTools'](arg1);
}

export function ListToolPlugins() {
  return window['go']['main']['ToolStoreWrapper']['ListToolPlugins']();
}

export function MapToolTarget(arg1) {
  return window['go']['main']['ToolStoreWrapper']['MapToolTarget'](arg1);
}

export function ResolveToolTarget(arg1) {
  return window['go']['main']['ToolStoreWrapper']['ResolveToolTarget'](arg1);
}

export function SetToolEnabled(arg1, arg2, arg3) {
  return window['go']['main']['ToolStoreWrapper']['SetToolEnabled'](arg1, arg2, arg3);
}

export function SetToolPluginEnabled(arg1, arg2, arg3) {
  return window['go']['main']['ToolStoreWrapper']['SetToolPluginEnabled'](arg1, arg2, arg3);
}
