// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {aggregate} from '../models';
import {spec} from '../models';
import {main} from '../models';
import {runtime} from '../models';
import {model} from '../models';
import {composition} from '../models';
import {consumerapi} from '../models';

export function HydrateInferenceToolChoice(arg1:aggregate.ToolSelection):Promise<spec.ToolChoice>;

export function InvokeMappedTool(arg1:main.ToolAggregateInvokeRequest):Promise<runtime.InvokeResponse>;

export function MapToolTarget(arg1:model.ArtifactRef):Promise<composition.MappedTarget>;

export function ResolveMappedTool(arg1:composition.MappedTarget):Promise<consumerapi.ResolvedToolView>;
