// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {llmtoolsutil} from '../models';

export function InvokeTool(arg1:llmtoolsutil.InvokeRequest):Promise<llmtoolsutil.InvokeResponse>;
