// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HydrateInferenceToolChoice(arg1) {
  return window['go']['main']['ToolAggregateWrapper']['HydrateInferenceToolChoice'](arg1);
}

export function InvokeMappedTool(arg1) {
  return window['go']['main']['ToolAggregateWrapper']['InvokeMappedTool'](arg1);
}

export function MapToolTarget(arg1) {
  return window['go']['main']['ToolAggregateWrapper']['MapToolTarget'](arg1);
}

export function ResolveMappedTool(arg1) {
  return window['go']['main']['ToolAggregateWrapper']['ResolveMappedTool'](arg1);
}
