// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spec} from '../models';

export function InvokeTool(arg1:spec.InvokeToolRequest):Promise<spec.InvokeToolResponse>;
