// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTool(arg1) {
  return window['go']['main']['ToolStoreWrapper']['GetTool'](arg1);
}

export function ListToolBundles(arg1) {
  return window['go']['main']['ToolStoreWrapper']['ListToolBundles'](arg1);
}

export function ListTools(arg1) {
  return window['go']['main']['ToolStoreWrapper']['ListTools'](arg1);
}

export function PatchTool(arg1) {
  return window['go']['main']['ToolStoreWrapper']['PatchTool'](arg1);
}

export function PatchToolBundle(arg1) {
  return window['go']['main']['ToolStoreWrapper']['PatchToolBundle'](arg1);
}

export function ResolveMappedToolTarget(arg1) {
  return window['go']['main']['ToolStoreWrapper']['ResolveMappedToolTarget'](arg1);
}
