// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTool(arg1) {
  return window['go']['main']['ToolStoreWrapper']['GetTool'](arg1);
}

export function GetToolCollection(arg1) {
  return window['go']['main']['ToolStoreWrapper']['GetToolCollection'](arg1);
}

export function ListCollectionTools(arg1) {
  return window['go']['main']['ToolStoreWrapper']['ListCollectionTools'](arg1);
}

export function ListToolCollections() {
  return window['go']['main']['ToolStoreWrapper']['ListToolCollections']();
}

export function SetToolCollectionEnabled(arg1, arg2, arg3) {
  return window['go']['main']['ToolStoreWrapper']['SetToolCollectionEnabled'](arg1, arg2, arg3);
}

export function SetToolEnabled(arg1, arg2, arg3) {
  return window['go']['main']['ToolStoreWrapper']['SetToolEnabled'](arg1, arg2, arg3);
}
