// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {runtime} from '../models';

export function InvokeTool(arg1:main.ToolRuntimeInvokeRequest):Promise<runtime.InvokeResponse>;
