// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {model} from '../models';

export function GetWorkspaceDefaultPolicy():Promise<workspace.WorkspaceDefaultPolicyView>;

export function GetWorkspaceDirectory(arg1:workspace.WorkspaceDirectoryRef):Promise<workspace.WorkspaceDirectoryView>;

export function ListWorkspaceDirectories(arg1:workspace.WorkspacePageRequest):Promise<workspace.WorkspacePage>;

export function ListWorkspaceDirectoryArtifacts(arg1:workspace.WorkspaceDirectoryRef):Promise<Array<workspace.WorkspaceArtifactView>>;

export function RefreshWorkspaceDirectory(arg1:workspace.WorkspaceDirectoryRef):Promise<workspace.WorkspaceDirectoryView>;

export function RegisterWorkspaceDirectory(arg1:string):Promise<workspace.WorkspaceDirectoryView>;

export function RemoveWorkspaceDirectory(arg1:workspace.WorkspaceDirectoryRef,arg2:number):Promise<void>;

export function SetWorkspaceDirectoryArtifactEnabled(arg1:workspace.WorkspaceDirectoryRef,arg2:model.ArtifactRef,arg3:number,arg4:boolean):Promise<workspace.WorkspaceArtifactView>;

export function SetWorkspaceDirectoryEnabled(arg1:workspace.WorkspaceDirectoryRef,arg2:number,arg3:boolean):Promise<workspace.WorkspaceDirectoryView>;
