// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdoptWorkspaceOccurrence(arg1) {
  return window['go']['main']['WorkspaceWrapper']['AdoptWorkspaceOccurrence'](arg1);
}

export function AttachWorkspaceSource(arg1) {
  return window['go']['main']['WorkspaceWrapper']['AttachWorkspaceSource'](arg1);
}

export function ComposeWorkspaceContext(arg1) {
  return window['go']['main']['WorkspaceWrapper']['ComposeWorkspaceContext'](arg1);
}

export function ComposeWorkspaceLoadPlan(arg1) {
  return window['go']['main']['WorkspaceWrapper']['ComposeWorkspaceLoadPlan'](arg1);
}

export function CreateEmptyWorkspace(arg1) {
  return window['go']['main']['WorkspaceWrapper']['CreateEmptyWorkspace'](arg1);
}

export function CreateFilesystemWorkspace(arg1) {
  return window['go']['main']['WorkspaceWrapper']['CreateFilesystemWorkspace'](arg1);
}

export function DetachWorkspaceSource(arg1) {
  return window['go']['main']['WorkspaceWrapper']['DetachWorkspaceSource'](arg1);
}

export function GetShareableWorkspaceDocument(arg1) {
  return window['go']['main']['WorkspaceWrapper']['GetShareableWorkspaceDocument'](arg1);
}

export function GetWorkspace(arg1) {
  return window['go']['main']['WorkspaceWrapper']['GetWorkspace'](arg1);
}

export function GetWorkspaceArtifact(arg1) {
  return window['go']['main']['WorkspaceWrapper']['GetWorkspaceArtifact'](arg1);
}

export function GetWorkspaceCatalog(arg1) {
  return window['go']['main']['WorkspaceWrapper']['GetWorkspaceCatalog'](arg1);
}

export function ListWorkspaceArtifacts(arg1) {
  return window['go']['main']['WorkspaceWrapper']['ListWorkspaceArtifacts'](arg1);
}

export function ListWorkspaceContexts(arg1) {
  return window['go']['main']['WorkspaceWrapper']['ListWorkspaceContexts'](arg1);
}

export function ListWorkspaceSkills(arg1) {
  return window['go']['main']['WorkspaceWrapper']['ListWorkspaceSkills'](arg1);
}

export function ListWorkspaceSuppressions(arg1) {
  return window['go']['main']['WorkspaceWrapper']['ListWorkspaceSuppressions'](arg1);
}

export function ListWorkspaces(arg1) {
  return window['go']['main']['WorkspaceWrapper']['ListWorkspaces'](arg1);
}

export function LoadWorkspaceContexts(arg1) {
  return window['go']['main']['WorkspaceWrapper']['LoadWorkspaceContexts'](arg1);
}

export function LoadWorkspaceSkills(arg1) {
  return window['go']['main']['WorkspaceWrapper']['LoadWorkspaceSkills'](arg1);
}

export function PinWorkspaceArtifact(arg1) {
  return window['go']['main']['WorkspaceWrapper']['PinWorkspaceArtifact'](arg1);
}

export function PurgeWorkspace(arg1) {
  return window['go']['main']['WorkspaceWrapper']['PurgeWorkspace'](arg1);
}

export function PurgeWorkspaceArtifact(arg1) {
  return window['go']['main']['WorkspaceWrapper']['PurgeWorkspaceArtifact'](arg1);
}

export function RefreshWorkspace(arg1) {
  return window['go']['main']['WorkspaceWrapper']['RefreshWorkspace'](arg1);
}

export function ReplaceWorkspacePrimarySource(arg1) {
  return window['go']['main']['WorkspaceWrapper']['ReplaceWorkspacePrimarySource'](arg1);
}

export function ResolveWorkspaceResource(arg1) {
  return window['go']['main']['WorkspaceWrapper']['ResolveWorkspaceResource'](arg1);
}

export function RetireWorkspace(arg1) {
  return window['go']['main']['WorkspaceWrapper']['RetireWorkspace'](arg1);
}

export function SetWorkspaceArtifactEnabled(arg1) {
  return window['go']['main']['WorkspaceWrapper']['SetWorkspaceArtifactEnabled'](arg1);
}

export function SetWorkspaceArtifactRuntimeDisabled(arg1) {
  return window['go']['main']['WorkspaceWrapper']['SetWorkspaceArtifactRuntimeDisabled'](arg1);
}

export function SetWorkspacePrimarySource(arg1) {
  return window['go']['main']['WorkspaceWrapper']['SetWorkspacePrimarySource'](arg1);
}

export function StoreShareableWorkspaceDocument(arg1) {
  return window['go']['main']['WorkspaceWrapper']['StoreShareableWorkspaceDocument'](arg1);
}

export function SuppressWorkspaceBinding(arg1) {
  return window['go']['main']['WorkspaceWrapper']['SuppressWorkspaceBinding'](arg1);
}

export function UnadoptWorkspaceArtifact(arg1) {
  return window['go']['main']['WorkspaceWrapper']['UnadoptWorkspaceArtifact'](arg1);
}

export function UnsuppressWorkspaceBinding(arg1) {
  return window['go']['main']['WorkspaceWrapper']['UnsuppressWorkspaceBinding'](arg1);
}

export function UpdateWorkspace(arg1) {
  return window['go']['main']['WorkspaceWrapper']['UpdateWorkspace'](arg1);
}

export function UpdateWorkspaceAttachment(arg1) {
  return window['go']['main']['WorkspaceWrapper']['UpdateWorkspaceAttachment'](arg1);
}
