// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {consumerapi} from '../models';
import {root} from '../models';
import {artifact} from '../models';
import {domain} from '../models';
import {source} from '../models';
import {resolve} from '../models';

export function AddWorkspacePath(arg1:consumerapi.WorkspacePathRegistration):Promise<consumerapi.WorkspacePathRegistrationResult>;

export function CreateWorkspaceRoot(arg1:root.RootDraft):Promise<root.Root>;

export function GetWorkspace(arg1:artifact.ArtifactRef):Promise<domain.WorkspaceView>;

export function ListWorkspaceArtifacts(arg1:artifact.ArtifactRef):Promise<Array<artifact.Artifact>>;

export function ListWorkspaceRoots():Promise<Array<root.Root>>;

export function ListWorkspaces(arg1:root.RootID):Promise<Array<domain.WorkspaceView>>;

export function ListWorkspacesForManagement():Promise<Array<domain.WorkspaceView>>;

export function LoadWorkspace(arg1:artifact.ArtifactRef):Promise<consumerapi.WorkspaceLoad>;

export function RefreshWorkspace(arg1:artifact.ArtifactRef):Promise<consumerapi.WorkspaceRefresh>;

export function RegisterFilesystemWorkspaceSource(arg1:consumerapi.FilesystemSourceRegistration):Promise<source.Summary>;

export function ResolveWorkspaceArtifactCapabilities(arg1:artifact.ArtifactRef):Promise<resolve.CapabilityPlan>;

export function ResolveWorkspaceCapabilities(arg1:artifact.ArtifactRef):Promise<resolve.CapabilityPlan>;

export function SetWorkspaceArtifactEnabled(arg1:artifact.ArtifactRef,arg2:artifact.ArtifactRef,arg3:number,arg4:boolean):Promise<consumerapi.WorkspaceArtifactView>;
