// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorkspacePath(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['AddWorkspacePath'](arg1);
}

export function CreateWorkspaceRoot(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['CreateWorkspaceRoot'](arg1);
}

export function GetWorkspace(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['GetWorkspace'](arg1);
}

export function ListWorkspaceArtifacts(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['ListWorkspaceArtifacts'](arg1);
}

export function ListWorkspaceRoots() {
  return window['go']['main']['WorkspaceStoreWrapper']['ListWorkspaceRoots']();
}

export function ListWorkspaces(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['ListWorkspaces'](arg1);
}

export function ListWorkspacesForManagement() {
  return window['go']['main']['WorkspaceStoreWrapper']['ListWorkspacesForManagement']();
}

export function LoadWorkspace(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['LoadWorkspace'](arg1);
}

export function RefreshWorkspace(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['RefreshWorkspace'](arg1);
}

export function RegisterFilesystemWorkspaceSource(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['RegisterFilesystemWorkspaceSource'](arg1);
}

export function ResolveWorkspaceArtifactCapabilities(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['ResolveWorkspaceArtifactCapabilities'](arg1);
}

export function ResolveWorkspaceCapabilities(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['ResolveWorkspaceCapabilities'](arg1);
}

export function SetWorkspaceArtifactEnabled(arg1, arg2, arg3, arg4) {
  return window['go']['main']['WorkspaceStoreWrapper']['SetWorkspaceArtifactEnabled'](arg1, arg2, arg3, arg4);
}
