// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {consumerapi} from '../models';

export function ComposeWorkspacePrompt(arg1:model.ArtifactRef,arg2:Array<model.ArtifactRef>):Promise<consumerapi.WorkspacePromptPlan>;

export function LoadWorkspaceMCPServers(arg1:model.ArtifactRef,arg2:Array<model.ArtifactRef>):Promise<consumerapi.WorkspaceMCPServerLoadPlan>;

export function LoadWorkspaceSkills(arg1:model.ArtifactRef,arg2:Array<model.ArtifactRef>):Promise<consumerapi.WorkspaceSkillLoadPlan>;

export function ResolveWorkspaceRuntimePlan(arg1:model.ArtifactRef,arg2:consumerapi.WorkspaceRuntimeSelection):Promise<consumerapi.WorkspaceRuntimePlan>;
