// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachWorkspaceSource(arg1) {
  return window['go']['main']['WorkspaceWrapper']['AttachWorkspaceSource'](arg1);
}

export function ComposeWorkspaceContext(arg1) {
  return window['go']['main']['WorkspaceWrapper']['ComposeWorkspaceContext'](arg1);
}

export function CreateEmptyWorkspace(arg1) {
  return window['go']['main']['WorkspaceWrapper']['CreateEmptyWorkspace'](arg1);
}

export function CreateFilesystemWorkspace(arg1) {
  return window['go']['main']['WorkspaceWrapper']['CreateFilesystemWorkspace'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['WorkspaceWrapper']['DeleteWorkspace'](arg1);
}

export function DeleteWorkspaceRecord(arg1) {
  return window['go']['main']['WorkspaceWrapper']['DeleteWorkspaceRecord'](arg1);
}

export function DetachWorkspaceSource(arg1) {
  return window['go']['main']['WorkspaceWrapper']['DetachWorkspaceSource'](arg1);
}

export function FollowWorkspaceRecord(arg1) {
  return window['go']['main']['WorkspaceWrapper']['FollowWorkspaceRecord'](arg1);
}

export function GetWorkspace(arg1) {
  return window['go']['main']['WorkspaceWrapper']['GetWorkspace'](arg1);
}

export function GetWorkspaceCatalog(arg1) {
  return window['go']['main']['WorkspaceWrapper']['GetWorkspaceCatalog'](arg1);
}

export function GetWorkspaceRecord(arg1) {
  return window['go']['main']['WorkspaceWrapper']['GetWorkspaceRecord'](arg1);
}

export function ListWorkspaceContexts(arg1) {
  return window['go']['main']['WorkspaceWrapper']['ListWorkspaceContexts'](arg1);
}

export function ListWorkspaceSkills(arg1) {
  return window['go']['main']['WorkspaceWrapper']['ListWorkspaceSkills'](arg1);
}

export function ListWorkspaces(arg1) {
  return window['go']['main']['WorkspaceWrapper']['ListWorkspaces'](arg1);
}

export function LoadWorkspaceContexts(arg1) {
  return window['go']['main']['WorkspaceWrapper']['LoadWorkspaceContexts'](arg1);
}

export function LoadWorkspaceSkills(arg1) {
  return window['go']['main']['WorkspaceWrapper']['LoadWorkspaceSkills'](arg1);
}

export function PinWorkspaceRecord(arg1) {
  return window['go']['main']['WorkspaceWrapper']['PinWorkspaceRecord'](arg1);
}

export function RefreshWorkspace(arg1) {
  return window['go']['main']['WorkspaceWrapper']['RefreshWorkspace'](arg1);
}

export function SetWorkspaceRecordEnabled(arg1) {
  return window['go']['main']['WorkspaceWrapper']['SetWorkspaceRecordEnabled'](arg1);
}

export function UpdateWorkspace(arg1) {
  return window['go']['main']['WorkspaceWrapper']['UpdateWorkspace'](arg1);
}

export function UpdateWorkspaceAttachment(arg1) {
  return window['go']['main']['WorkspaceWrapper']['UpdateWorkspaceAttachment'](arg1);
}

export function UpdateWorkspaceRecordData(arg1) {
  return window['go']['main']['WorkspaceWrapper']['UpdateWorkspaceRecordData'](arg1);
}
