// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWorkspaceDefaultPolicy() {
  return window['go']['main']['WorkspaceStoreWrapper']['GetWorkspaceDefaultPolicy']();
}

export function GetWorkspaceDirectory(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['GetWorkspaceDirectory'](arg1);
}

export function ListWorkspaceDirectories(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['ListWorkspaceDirectories'](arg1);
}

export function ListWorkspaceDirectoryArtifacts(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['ListWorkspaceDirectoryArtifacts'](arg1);
}

export function RefreshWorkspaceDirectory(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['RefreshWorkspaceDirectory'](arg1);
}

export function RegisterWorkspaceDirectory(arg1) {
  return window['go']['main']['WorkspaceStoreWrapper']['RegisterWorkspaceDirectory'](arg1);
}

export function RemoveWorkspaceDirectory(arg1, arg2) {
  return window['go']['main']['WorkspaceStoreWrapper']['RemoveWorkspaceDirectory'](arg1, arg2);
}

export function SetWorkspaceDirectoryArtifactEnabled(arg1, arg2, arg3, arg4) {
  return window['go']['main']['WorkspaceStoreWrapper']['SetWorkspaceDirectoryArtifactEnabled'](arg1, arg2, arg3, arg4);
}

export function SetWorkspaceDirectoryEnabled(arg1, arg2, arg3) {
  return window['go']['main']['WorkspaceStoreWrapper']['SetWorkspaceDirectoryEnabled'](arg1, arg2, arg3);
}
