// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {workspace} from '../models';

export function ComposeWorkspacePrompt(arg1:model.ArtifactRef,arg2:Array<model.ArtifactRef>):Promise<workspace.WorkspacePromptPlan>;

export function LoadWorkspaceMCPServers(arg1:model.ArtifactRef,arg2:Array<model.ArtifactRef>):Promise<workspace.WorkspaceMCPServerLoadPlan>;

export function LoadWorkspaceSkills(arg1:model.ArtifactRef,arg2:Array<model.ArtifactRef>):Promise<workspace.WorkspaceSkillLoadPlan>;

export function ResolveWorkspaceRuntimePlan(arg1:model.ArtifactRef,arg2:workspace.WorkspaceRuntimeSelection):Promise<workspace.WorkspaceRuntimePlan>;
