// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {artifact} from '../models';
import {consumerapi} from '../models';

export function SetWorkspaceArtifactRuntimeDisabled(arg1:artifact.ArtifactRef,arg2:artifact.ArtifactRef,arg3:number,arg4:boolean):Promise<consumerapi.WorkspaceArtifactView>;
