// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {consumerapi} from '../models';
import {artifact} from '../models';

export function GetWorkspaceDefaultPolicy():Promise<consumerapi.WorkspaceDefaultPolicyView>;

export function GetWorkspaceDirectory(arg1:consumerapi.WorkspaceDirectoryRef):Promise<consumerapi.WorkspaceDirectoryView>;

export function ListWorkspaceDirectories(arg1:consumerapi.WorkspacePageRequest):Promise<consumerapi.WorkspacePage>;

export function ListWorkspaceDirectoryArtifacts(arg1:consumerapi.WorkspaceDirectoryRef):Promise<Array<consumerapi.WorkspaceArtifactView>>;

export function RefreshWorkspaceDirectory(arg1:consumerapi.WorkspaceDirectoryRef):Promise<consumerapi.WorkspaceDirectoryView>;

export function RegisterWorkspaceDirectory(arg1:string):Promise<consumerapi.WorkspaceDirectoryView>;

export function RemoveWorkspaceDirectory(arg1:consumerapi.WorkspaceDirectoryRef,arg2:number):Promise<void>;

export function SetWorkspaceDirectoryArtifactEnabled(arg1:consumerapi.WorkspaceDirectoryRef,arg2:artifact.ArtifactRef,arg3:number,arg4:boolean):Promise<consumerapi.WorkspaceArtifactView>;

export function SetWorkspaceDirectoryEnabled(arg1:consumerapi.WorkspaceDirectoryRef,arg2:number,arg3:boolean):Promise<consumerapi.WorkspaceDirectoryView>;
