// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ComposeWorkspacePrompt(arg1, arg2) {
  return window['go']['main']['WorkspaceRuntimeWrapper']['ComposeWorkspacePrompt'](arg1, arg2);
}

export function LoadWorkspaceMCPServers(arg1, arg2) {
  return window['go']['main']['WorkspaceRuntimeWrapper']['LoadWorkspaceMCPServers'](arg1, arg2);
}

export function LoadWorkspaceSkills(arg1, arg2) {
  return window['go']['main']['WorkspaceRuntimeWrapper']['LoadWorkspaceSkills'](arg1, arg2);
}

export function ResolveWorkspaceRuntimePlan(arg1, arg2) {
  return window['go']['main']['WorkspaceRuntimeWrapper']['ResolveWorkspaceRuntimePlan'](arg1, arg2);
}
