// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';

export function AdoptWorkspaceOccurrence(arg1:workspace.AdoptWorkspaceOccurrenceRequest):Promise<workspace.AdoptWorkspaceOccurrenceResponse>;

export function AttachWorkspaceSource(arg1:workspace.AttachWorkspaceSourceRequest):Promise<workspace.AttachWorkspaceSourceResponse>;

export function ComposeWorkspaceContext(arg1:workspace.ComposeWorkspaceContextRequest):Promise<workspace.ComposeWorkspaceContextResponse>;

export function ComposeWorkspaceLoadPlan(arg1:workspace.ComposeWorkspaceLoadPlanRequest):Promise<workspace.ComposeWorkspaceLoadPlanResponse>;

export function CreateEmptyWorkspace(arg1:workspace.CreateEmptyWorkspaceRequest):Promise<workspace.CreateEmptyWorkspaceResponse>;

export function CreateFilesystemWorkspace(arg1:workspace.CreateFilesystemWorkspaceRequest):Promise<workspace.CreateFilesystemWorkspaceResponse>;

export function DetachWorkspaceSource(arg1:workspace.DetachWorkspaceSourceRequest):Promise<workspace.DetachWorkspaceSourceResponse>;

export function GetWorkspace(arg1:workspace.GetWorkspaceRequest):Promise<workspace.GetWorkspaceResponse>;

export function GetWorkspaceArtifact(arg1:workspace.GetWorkspaceArtifactRequest):Promise<workspace.GetWorkspaceArtifactResponse>;

export function GetWorkspaceCatalog(arg1:workspace.GetWorkspaceCatalogRequest):Promise<workspace.GetWorkspaceCatalogResponse>;

export function ListWorkspaceArtifacts(arg1:workspace.ListWorkspaceArtifactsRequest):Promise<workspace.ListWorkspaceArtifactsResponse>;

export function ListWorkspaceContexts(arg1:workspace.ListWorkspaceContextsRequest):Promise<workspace.ListWorkspaceContextsResponse>;

export function ListWorkspaceSkills(arg1:workspace.ListWorkspaceSkillsRequest):Promise<workspace.ListWorkspaceSkillsResponse>;

export function ListWorkspaceSuppressions(arg1:workspace.ListWorkspaceSuppressionsRequest):Promise<workspace.ListWorkspaceSuppressionsResponse>;

export function ListWorkspaces(arg1:workspace.ListWorkspacesRequest):Promise<workspace.ListWorkspacesResponse>;

export function LoadWorkspaceContexts(arg1:workspace.LoadWorkspaceContextsRequest):Promise<workspace.LoadWorkspaceContextsResponse>;

export function LoadWorkspaceSkills(arg1:workspace.LoadWorkspaceSkillsRequest):Promise<workspace.LoadWorkspaceSkillsResponse>;

export function PinWorkspaceArtifact(arg1:workspace.PinWorkspaceArtifactRequest):Promise<workspace.PinWorkspaceArtifactResponse>;

export function PurgeWorkspace(arg1:workspace.PurgeWorkspaceRequest):Promise<workspace.PurgeWorkspaceResponse>;

export function PurgeWorkspaceArtifact(arg1:workspace.PurgeWorkspaceArtifactRequest):Promise<workspace.PurgeWorkspaceArtifactResponse>;

export function RefreshWorkspace(arg1:workspace.RefreshWorkspaceRequest):Promise<workspace.RefreshWorkspaceResponse>;

export function ReplaceWorkspacePrimarySource(arg1:workspace.ReplaceWorkspacePrimarySourceRequest):Promise<workspace.ReplaceWorkspacePrimarySourceResponse>;

export function ResolveWorkspaceResource(arg1:workspace.ResolveWorkspaceResourceRequest):Promise<workspace.ResolveWorkspaceResourceResponse>;

export function RetireWorkspace(arg1:workspace.RetireWorkspaceRequest):Promise<workspace.RetireWorkspaceResponse>;

export function SetWorkspaceArtifactEnabled(arg1:workspace.SetWorkspaceArtifactEnabledRequest):Promise<workspace.SetWorkspaceArtifactEnabledResponse>;

export function SetWorkspaceArtifactRuntimeDisabled(arg1:workspace.SetWorkspaceArtifactRuntimeDisabledRequest):Promise<workspace.SetWorkspaceArtifactRuntimeDisabledResponse>;

export function SetWorkspacePrimarySource(arg1:workspace.SetWorkspacePrimarySourceRequest):Promise<workspace.SetWorkspacePrimarySourceResponse>;

export function SuppressWorkspaceBinding(arg1:workspace.SuppressWorkspaceBindingRequest):Promise<workspace.SuppressWorkspaceBindingResponse>;

export function UnadoptWorkspaceArtifact(arg1:workspace.UnadoptWorkspaceArtifactRequest):Promise<workspace.UnadoptWorkspaceArtifactResponse>;

export function UnsuppressWorkspaceBinding(arg1:workspace.UnsuppressWorkspaceBindingRequest):Promise<workspace.UnsuppressWorkspaceBindingResponse>;

export function UpdateWorkspace(arg1:workspace.UpdateWorkspaceRequest):Promise<workspace.UpdateWorkspaceResponse>;

export function UpdateWorkspaceAttachment(arg1:workspace.UpdateWorkspaceAttachmentRequest):Promise<workspace.UpdateWorkspaceAttachmentResponse>;
