package model

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
	"time"
	"unicode/utf8"

	artifact "github.com/flexigpt/flexigpt-app/internal/artifactory-go/store/artifact/model"
	overlay "github.com/flexigpt/flexigpt-app/internal/artifactory-go/store/overlay/model"
	"github.com/flexigpt/flexigpt-app/internal/artifactory-go/store/spec"
	"github.com/flexigpt/flexigpt-app/internal/uuidutil"
)

const refPrefix = "secret.v1/"

// Ref identifies one opaque Artifact Store secret value.
//
// The ref is generated by Artifact Store and persisted in SQLite metadata.
// It is not derived from an Artifact name, source path, logical name, or
// secret value.
type Ref string

func NewRef() Ref {
	return Ref(refPrefix + uuidutil.NewUUIDv7())
}

func (v Ref) Validate() error {
	value := string(v)
	if !strings.HasPrefix(value, refPrefix) {
		return fmt.Errorf(
			"%w: secret reference has an unsupported format",
			spec.ErrInvalid,
		)
	}
	if err := uuidutil.ValidateUUIDv7(
		strings.TrimPrefix(value, refPrefix),
	); err != nil {
		return fmt.Errorf("secret reference: %w", err)
	}
	return nil
}

// ID returns the opaque UUID portion of a validated secret reference.
func (v Ref) ID() (string, error) {
	if err := v.Validate(); err != nil {
		return "", err
	}
	return strings.TrimPrefix(string(v), refPrefix), nil
}

// Slot identifies one feature-owned secret injection point.
//
// Examples include apiKey, header.authorization, and env.client-secret.
// Artifact Store validates only the stable identifier shape. The feature owns
// the meaning and whether a slot is legal for a selected Artifact.
type Slot string

func (v Slot) Validate() error {
	return spec.ValidateIdentifier(
		"secret binding slot",
		string(v),
		spec.MaxKindBytes,
	)
}

// BindingKey identifies one Artifact-local secret reference.
type BindingKey struct {
	Artifact  artifact.ArtifactRef `json:"artifact"`
	Namespace overlay.Namespace    `json:"namespace"`
	Slot      Slot                 `json:"slot"`
}

func (k BindingKey) Validate() error {
	if err := k.Artifact.Validate(); err != nil {
		return err
	}
	if err := k.Namespace.Validate(); err != nil {
		return err
	}
	return k.Slot.Validate()
}

// Binding is public-safe metadata for one Artifact-local secret binding.
//
// Ref and SHA256 are metadata. Value is never present in this type.
type Binding struct {
	Key BindingKey `json:"key"`

	Ref    *Ref   `json:"ref,omitempty"`
	SHA256 string `json:"sha256,omitempty"`

	Revision   uint64    `json:"revision"`
	CreatedAt  time.Time `json:"createdAt"`
	ModifiedAt time.Time `json:"modifiedAt"`
}

func (b Binding) Active() bool {
	return b.Ref != nil
}

func (b Binding) Validate() error {
	if err := b.Key.Validate(); err != nil {
		return err
	}
	if b.Ref == nil {
		if b.SHA256 != "" {
			return fmt.Errorf(
				"%w: cleared secret binding cannot retain SHA-256 metadata",
				spec.ErrInvalid,
			)
		}
	} else {
		if err := b.Ref.Validate(); err != nil {
			return err
		}
		if err := ValidateSHA256(b.SHA256); err != nil {
			return err
		}
	}

	if b.Revision == 0 {
		return fmt.Errorf(
			"%w: secret binding revision is required",
			spec.ErrInvalid,
		)
	}
	if b.CreatedAt.IsZero() || b.ModifiedAt.IsZero() {
		return fmt.Errorf(
			"%w: secret binding timestamps are required",
			spec.ErrInvalid,
		)
	}
	if b.ModifiedAt.Before(b.CreatedAt) {
		return fmt.Errorf(
			"%w: secret binding modified time precedes creation",
			spec.ErrInvalid,
		)
	}
	return nil
}

func (b Binding) Clone() Binding {
	output := b
	if b.Ref != nil {
		value := *b.Ref
		output.Ref = &value
	}
	return output
}

// ReplaceBindingRequest stores a new secret value and atomically changes the
// Artifact-local reference after the value is successfully staged.
type ReplaceBindingRequest struct {
	Key BindingKey `json:"key"`

	ExpectedArtifactRevision uint64 `json:"expectedArtifactRevision"`
	ExpectedBindingRevision  uint64 `json:"expectedBindingRevision"`

	// Value is runtime-only command input. It is never serialized by Artifact
	// Store metadata repositories.
	Value string `json:"-"`
}

func (r ReplaceBindingRequest) Validate() error {
	if err := r.Key.Validate(); err != nil {
		return err
	}
	if r.ExpectedArtifactRevision == 0 {
		return fmt.Errorf(
			"%w: expected Artifact revision is required",
			spec.ErrInvalid,
		)
	}
	return ValidateValue(r.Value)
}

// ClearBindingRequest detaches one secret binding and queues physical secret
// cleanup after metadata publication.
type ClearBindingRequest struct {
	Key BindingKey `json:"key"`

	ExpectedArtifactRevision uint64 `json:"expectedArtifactRevision"`
	ExpectedBindingRevision  uint64 `json:"expectedBindingRevision"`
}

func (r ClearBindingRequest) Validate() error {
	if err := r.Key.Validate(); err != nil {
		return err
	}
	if r.ExpectedArtifactRevision == 0 {
		return fmt.Errorf(
			"%w: expected Artifact revision is required",
			spec.ErrInvalid,
		)
	}
	return nil
}

// RecordState is internal metadata lifecycle state for one physical secret
// value. It never appears in public feature transport responses.
type RecordState string

const (
	RecordStatePending RecordState = "pending"
	RecordStateActive  RecordState = "active"
	RecordStateCleanup RecordState = "cleanup"
)

func (s RecordState) Validate() error {
	switch s {
	case RecordStatePending, RecordStateActive, RecordStateCleanup:
		return nil
	default:
		return fmt.Errorf(
			"%w: invalid secret record state %q",
			spec.ErrInvalid,
			s,
		)
	}
}

// Record is non-secret metadata for one physical secret value.
type Record struct {
	Ref       Ref         `json:"ref"`
	StoreName string      `json:"storeName"`
	SHA256    string      `json:"sha256"`
	State     RecordState `json:"state"`

	CreatedAt  time.Time `json:"createdAt"`
	ModifiedAt time.Time `json:"modifiedAt"`
}

func (r Record) Validate() error {
	if err := r.Ref.Validate(); err != nil {
		return err
	}
	if err := spec.ValidateIdentifier(
		"secret value store name",
		r.StoreName,
		spec.MaxKindBytes,
	); err != nil {
		return err
	}
	if err := ValidateSHA256(r.SHA256); err != nil {
		return err
	}
	if err := r.State.Validate(); err != nil {
		return err
	}
	if r.CreatedAt.IsZero() || r.ModifiedAt.IsZero() {
		return fmt.Errorf(
			"%w: secret record timestamps are required",
			spec.ErrInvalid,
		)
	}
	if r.ModifiedAt.Before(r.CreatedAt) {
		return fmt.Errorf(
			"%w: secret record modified time precedes creation",
			spec.ErrInvalid,
		)
	}
	return nil
}

func (r Record) Clone() Record {
	return r
}

// Cleanup is one durable request to remove an unreferenced physical secret
// value from the configured value store.
type Cleanup struct {
	Ref       Ref    `json:"ref"`
	StoreName string `json:"storeName"`

	Attempts   int       `json:"attempts"`
	LastError  string    `json:"lastError,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
	ModifiedAt time.Time `json:"modifiedAt"`
}

func (c Cleanup) Validate() error {
	if err := c.Ref.Validate(); err != nil {
		return err
	}
	if err := spec.ValidateIdentifier(
		"secret cleanup store name",
		c.StoreName,
		spec.MaxKindBytes,
	); err != nil {
		return err
	}
	if c.Attempts < 0 {
		return fmt.Errorf(
			"%w: secret cleanup attempts cannot be negative",
			spec.ErrInvalid,
		)
	}
	if err := spec.ValidateOptionalText(
		"secret cleanup error",
		c.LastError,
		spec.MaxDescriptionBytes,
	); err != nil {
		return err
	}
	if c.CreatedAt.IsZero() || c.ModifiedAt.IsZero() {
		return fmt.Errorf(
			"%w: secret cleanup timestamps are required",
			spec.ErrInvalid,
		)
	}
	if c.ModifiedAt.Before(c.CreatedAt) {
		return fmt.Errorf(
			"%w: secret cleanup modified time precedes creation",
			spec.ErrInvalid,
		)
	}
	return nil
}

// ValidateValue validates secret command input without including the value in
// an error message.
func ValidateValue(value string) error {
	if value == "" {
		return fmt.Errorf(
			"%w: secret value is required",
			spec.ErrInvalid,
		)
	}
	if len(value) > spec.MaxSecretBytes {
		return fmt.Errorf(
			"%w: secret value exceeds %d bytes",
			spec.ErrInvalid,
			spec.MaxSecretBytes,
		)
	}
	if !utf8.ValidString(value) {
		return fmt.Errorf(
			"%w: secret value must be valid UTF-8",
			spec.ErrInvalid,
		)
	}
	return nil
}

func SHA256(value string) string {
	sum := sha256.Sum256([]byte(value))
	return hex.EncodeToString(sum[:])
}

func ValidateSHA256(value string) error {
	if len(value) != sha256.Size*2 ||
		strings.ToLower(value) != value {
		return fmt.Errorf(
			"%w: invalid secret SHA-256 metadata",
			spec.ErrInvalid,
		)
	}
	if _, err := hex.DecodeString(value); err != nil {
		return fmt.Errorf(
			"%w: invalid secret SHA-256 metadata",
			spec.ErrInvalid,
		)
	}
	return nil
}
