import type { JSONRawString } from '@/lib/jsonschema_utils';

export function requireWailsBody<T>(body: T | null | undefined, operation: string): T {
	if (body === null || body === undefined) {
		throw new Error(`${operation} returned an empty response body.`);
	}
	return body;
}

export function toFrontendDate(value: unknown, field: string): Date {
	if (value instanceof Date) {
		return value;
	}

	if (typeof value === 'string' || typeof value === 'number') {
		const date = new Date(value);
		if (!Number.isNaN(date.getTime())) {
			return date;
		}
	}

	throw new Error(`Invalid date received for ${field}.`);
}

/**
 * `json.RawMessage` is generated by Wails as `number[]`, but it is transported
 * as raw JSON. Send the parsed JSON object, not an UTF-8 byte array.
 */
export function rawJSONObjectToWails(value: JSONRawString, field: string): unknown {
	let parsed: unknown;

	try {
		parsed = JSON.parse(value);
	} catch {
		throw new Error(`${field} must be valid JSON.`);
	}

	if (parsed === null || Array.isArray(parsed) || typeof parsed !== 'object') {
		throw new Error(`${field} must be a JSON object.`);
	}

	return parsed;
}

/**
 * Supports both Wails representations seen for `json.RawMessage`:
 *
 * - Raw JSON object
 * - Generated `number[]` byte representation
 */
export function rawJSONFromWails(value: unknown, field: string): JSONRawString {
	if (Array.isArray(value) && value.every(item => typeof item === 'number')) {
		const text = new TextDecoder().decode(Uint8Array.from(value));
		JSON.parse(text);
		return text;
	}

	if (typeof value === 'string') {
		JSON.parse(value);
		return value;
	}

	if (value === null || typeof value !== 'object') {
		throw new Error(`${field} is not valid JSON.`);
	}

	return JSON.stringify(value);
}

export function byteArrayToWails(value: Uint8Array): number[] {
	return [...value];
}
