import type { JSONRawString, JSONSchema } from '@/lib/jsonschema_utils';

const DEFAULT_MAX_PAGES = 1_000;

function isByte(value: unknown): value is number {
	return typeof value === 'number' && Number.isInteger(value) && value >= 0 && value <= 255;
}

/**
 * Wails transports Go string aliases as plain JavaScript strings. Validate
 * values at the bridge boundary before exposing frontend enum types.
 */
export function enumFromWails<T extends string>(value: unknown, enumValues: Record<string, T>, field: string): T {
	const allowed = Object.values(enumValues) as T[];

	if (typeof value !== 'string' || !allowed.includes(value as T)) {
		throw new Error(`Invalid ${field}: ${String(value)}`);
	}

	return value as T;
}

export function requireWailsArray<T = unknown>(value: unknown, field: string): T[] {
	if (!Array.isArray(value)) {
		throw new TypeError(`${field} returned an invalid array.`);
	}

	return value as T[];
}

export function requireWailsString(value: unknown, field: string): string {
	if (typeof value !== 'string') {
		throw new TypeError(`${field} returned an invalid string.`);
	}

	return value;
}

export function requireNonBlankString(value: string, field: string): string {
	if (value.trim().length === 0) {
		throw new Error(`${field} must not be empty.`);
	}

	return value;
}

export function omitUndefined<T extends Record<string, unknown>>(value: T): Partial<T> {
	return Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined)) as Partial<T>;
}

export async function collectAllPages<T>(
	fetchPage: (pageToken: string | undefined) => Promise<{ items: T[]; nextPageToken?: string }>,
	maxPages = DEFAULT_MAX_PAGES
): Promise<T[]> {
	const items: T[] = [];
	const seenTokens = new Set<string>();
	let pageToken: string | undefined;

	for (let page = 0; page < maxPages; page++) {
		const result = await fetchPage(pageToken);
		items.push(...result.items);

		if (!result.nextPageToken) {
			return items;
		}

		if (seenTokens.has(result.nextPageToken)) {
			throw new Error('Pagination response repeated a page token.');
		}

		seenTokens.add(result.nextPageToken);
		pageToken = result.nextPageToken;
	}

	throw new Error(`Pagination exceeded the ${maxPages}-page safety limit.`);
}

export function requireWailsBody<T>(body: T | null | undefined, operation: string): T {
	if (body === null || body === undefined) {
		throw new Error(`${operation} returned an empty response body.`);
	}
	return body;
}

export function optionalWailsBody<T>(body: T | null | undefined): T | undefined {
	return body === null || body === undefined ? undefined : body;
}

function createAbortError(): Error {
	if (typeof DOMException !== 'undefined') {
		return new DOMException('Aborted', 'AbortError');
	}

	const error = new Error('Aborted');
	error.name = 'AbortError';
	return error;
}

export function throwIfAborted(signal?: AbortSignal): void {
	if (signal?.aborted) {
		throw createAbortError();
	}
}

/**
 * `json.RawMessage` is generated by Wails as `number[]`, but it is transported
 * as raw JSON. Send the parsed JSON object, not an UTF-8 byte array.
 */
export function rawJSONObjectToWails(value: JSONRawString, field: string): unknown {
	if (typeof value !== 'string') {
		throw new TypeError(`${field} must be valid JSON.`);
	}

	let parsed: unknown;

	try {
		parsed = JSON.parse(value);
	} catch {
		throw new Error(`${field} must be valid JSON.`);
	}

	if (parsed === null || Array.isArray(parsed) || typeof parsed !== 'object') {
		throw new Error(`${field} must be a JSON object.`);
	}

	return parsed;
}

/**
 * Supports both Wails representations seen for `json.RawMessage`:
 *
 * - Raw JSON object
 * - Generated `number[]` byte representation
 */
export function rawJSONFromWails(value: unknown, field: string): JSONRawString {
	if (Array.isArray(value) && value.every(item => typeof item === 'number')) {
		if (
			!value.every(b => {
				return isByte(b);
			})
		) {
			throw new Error(`${field} contains an invalid byte array.`);
		}
		const text = new TextDecoder('utf-8', { fatal: true }).decode(Uint8Array.from(value));
		JSON.parse(text);
		return text;
	}

	if (typeof value === 'string') {
		JSON.parse(value);
		return value;
	}

	if (value === null || typeof value !== 'object') {
		throw new Error(`${field} is not valid JSON.`);
	}

	const serialized = JSON.stringify(value);
	if (serialized === undefined) {
		throw new Error(`${field} is not valid JSON.`);
	}

	return serialized;
}

export function rawJSONToWails(value: JSONRawString, field: string): string {
	if (typeof value !== 'string') {
		throw new TypeError(`${field} must be valid JSON.`);
	}

	try {
		JSON.parse(value);
	} catch {
		throw new Error(`${field} must be valid JSON.`);
	}

	return value;
}

export function jsonObjectFromWails(value: unknown, field: string): JSONSchema {
	const parsed = JSON.parse(rawJSONFromWails(value, field));

	if (parsed === null || Array.isArray(parsed) || typeof parsed !== 'object') {
		throw new Error(`${field} must be a JSON object.`);
	}

	return parsed as JSONSchema;
}

export function jsonObjectToWails(value: JSONSchema, field: string): string {
	if (value === null || Array.isArray(value) || typeof value !== 'object') {
		throw new Error(`${field} must be a JSON object.`);
	}

	const serialized = JSON.stringify(value);
	if (serialized === undefined) {
		throw new Error(`${field} must be a JSON object.`);
	}

	return serialized;
}

export function byteArrayToWails(value: Uint8Array): number[] {
	if (!(value instanceof Uint8Array)) {
		throw new Error('Expected a Uint8Array.');
	}

	return [...value];
}
