type: plugin
name: software-dev-templates
description: "Builtin software development template skills."
members:
  - type: skill
    name: diagrams-stage
    locator: ./diagrams-stage
  - type: skill
    name: fe-stack-react-vite
    locator: ./fe-stack-react-vite
  - type: skill
    name: go-table-tests
    locator: ./go-table-tests
